---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webhook-namecheap
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager-webhook-namecheap
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: webhook-namecheap
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
