apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api
    namespace: cert-manager
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:/kuGRfOkiANKBId1NSp1fdsxxPfbmMOFsm+z869kCPM=,iv:zrDgjsgMVPmNgFiZ6CTeNDSHSGIxjaDLbYoTp6wLnRo=,tag:ZI1lGC6VLIlWcUMu4q668g==,type:str]
    apiUser: ENC[AES256_GCM,data:ta2Fbv2rMIWG2Hj1Hg==,iv:qGyVlMVdLG/0bDXVFlKh6A7V2q0CJWHfnGCKVPj6kVU=,tag:qmqhBNe1Rb0u0VvXKT58MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWGFTQmljNlBOUDVxVU1o
            M0RwdVZBWWVxaHg1L3liWlMwZEF0UXkxdG5BCmxtWWtpVnNrQ294V2JoQ1BXdm5L
            KzZ2SFZkTmJ1N3M2WTdkTFV3ZGt5dTAKLS0tIGQ2MVozTittZmlIQ29MMCtmZHRn
            bTNzcERjRUdaOWdidmlrYktBSzNsNVEK+o5U37+Gwk7AfHD37tQYdbFMswxEvuzw
            9mIDRyD63uhMWmXekMUVdNIZsqzXRSolFAk253sonOQMlRiWg4gT0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-17T02:51:56Z"
    mac: ENC[AES256_GCM,data:9cLJZEfVu0VXcxvGNci711AXp0SoLh02ionUUtBSi1w0JwZF4ze2VFMDXtT66rr94x0XDdHv/0c1Q8eOw7Mi5j8LAHhOI2/56yFKyJxCrbsiBSMymNhwMoordb9UwTbdshxeh1794ovl0hBeJp2upuZ1P0LZai49ziFAHv7kN9A=,iv:wrSYDzdd9mjetd1gap+K5tYYQd73GMWTf69LMXXmsFU=,tag:6LjTiPusD84qNnaZm3QIvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
