---
# CN = mongodb-0
# DNS:mongodb-0.mongodb-headless.default.svc.cluster.local
# DNS:mongodb-0
# DNS:mongodb-headless
# DNS:localhost
# DNS:127.0.0.1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-0-cert
  namespace: default
spec:
  secretName: mongodb-0-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: mongodb-0
  dnsNames:
    - mongodb-0.mongodb-headless.default.svc.cluster.local
    - mongodb-0
    - mongodb-headless
    - localhost
  ipAddresses:
    - 127.0.0.1
---
# CN = mongodb-1
# DNS:mongodb-1.mongodb-headless.default.svc.cluster.local
# DNS:mongodb-1
# DNS:mongodb-headless
# DNS:localhost
# DNS:127.0.0.1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-1-cert
  namespace: default
spec:
  secretName: mongodb-1-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: mongodb-1
  dnsNames:
    - mongodb-1.mongodb-headless.default.svc.cluster.local
    - mongodb-1
    - mongodb-headless
    - localhost
  ipAddresses:
    - 127.0.0.1
---
# CN = mongodb-2
# DNS:mongodb-2.mongodb-headless.default.svc.cluster.local
# DNS:mongodb-2
# DNS:mongodb-headless
# DNS:localhost
# DNS:127.0.0.1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-2-cert
  namespace: default
spec:
  secretName: mongodb-2-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: mongodb-2
  dnsNames:
    - mongodb-2.mongodb-headless.default.svc.cluster.local
    - mongodb-2
    - mongodb-headless
    - localhost
  ipAddresses:
    - 127.0.0.1
