---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: networking
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cert-manager
      namespace: cert-manager
    - name: ingress-nginx
      namespace: networking
  releaseName: authentik
  targetNamespace: networking
  interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      envFrom:
        - secretRef:
            name: authentik-env-secrets
      volumeMounts:
        # Mappings:
        # assets/custom.css -> /web/dist/custom.css
        - name: custom-assets-custom-css
          mountPath: /web/dist/custom.css
          subPath: custom.css
          readOnly: true
        # assets/flow_background.jpg -> /web/dist/assets/images/flow_background.jpg
        - name: custom-assets-flow-background-jpg
          mountPath: /web/dist/assets/images/flow_background.jpg
          subPath: flow_background.jpg
          readOnly: true
        # assets/icon_left_brand.svg -> /web/dist/assets/icons/icon_left_brand.svg
        - name: custom-assets-icon-left-brand
          mountPath: /web/dist/assets/icons/icon_left_brand.svg
          subPath: icon_left_brand.svg
          readOnly: true
        # MontserratAlt1-Regular.ttf -> /web/dist/assets/fonts/montserratalt1/MontserratAlt1-Regular.ttf
        - name: custom-assets-montserrat-alt1-regular-ttf
          mountPath: /web/dist/assets/fonts/montserratalt1/MontserratAlt1-Regular.ttf
          subPath: MontserratAlt1-Regular.ttf
          readOnly: true
        # MontserratAlt1-Regular.woff -> /web/dist/assets/fonts/montserratalt1/MontserratAlt1-Regular.woff
        - name: custom-assets-montserrat-alt1-regular-woff
          mountPath: /web/dist/assets/fonts/montserratalt1/MontserratAlt1-Regular.woff
          subPath: MontserratAlt1-Regular.woff
          readOnly: true
        # MontserratAlt1-Regular.woff2 -> /web/dist/assets/fonts/montserratalt1/MontserratAlt1-Regular.woff2
        - name: custom-assets-montserrat-alt1-regular-woff2
          mountPath: /web/dist/assets/fonts/montserratalt1/MontserratAlt1-Regular.woff2
          subPath: MontserratAlt1-Regular.woff2
          readOnly: true
        # assets/theme-dark.css -> /web/dist/theme-dark.css
        - name: custom-assets-theme-dark-css
          mountPath: /web/dist/theme-dark.css
          subPath: theme-dark.css
          readOnly: true

      volumes:
        - name: custom-assets-custom-css
          configMap:
            name: authentik-assets-custom-css
        - name: custom-assets-flow-background-jpg
          configMap:
            name: authentik-assets-flow-background-jpg
        - name: custom-assets-icon-left-brand
          configMap:
            name: authentik-assets-icon-left-brand
        - name: custom-assets-montserrat-alt1-regular-ttf
          configMap:
            name: authentik-assets-montserrat-alt1-regular-ttf
        - name: custom-assets-montserrat-alt1-regular-woff
          configMap:
            name: authentik-assets-montserrat-alt1-regular-woff
        - name: custom-assets-montserrat-alt1-regular-woff2
          configMap:
            name: authentik-assets-montserrat-alt1-regular-woff2
        - name: custom-assets-theme-dark-css
          configMap:
            name: authentik-assets-theme-dark-css

    authentik:
      error_reporting:
        enabled: false
        send_pii: false
        environment: "nanabooboo"
      email:
        use_tls: true
        use_ssl: false
        timeout: 30
      postgresql:
        enabled: true

    server:
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 50
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Networking
          gethomepage.dev/name: Authentik
          gethomepage.dev/icon: authentik.png
          gethomepage.dev/pod-selector: app.kubernetes.io/name=authentik
          gethomepage.dev/widget.type: authentik
          gethomepage.dev/widget.url: http://authentik-server.networking.svc.cluster.local
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts: &hosts
          - "auth.${SECRET_DOMAIN}"
        tls:
          - hosts: *hosts
      startupProbe:
        initialDelaySeconds: 120
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 2Gi

    worker:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
        targetCPUUtilizationPercentage: 50
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1
      startupProbe:
        initialDelaySeconds: 120
      resources:
        requests:
          cpu: 500m
          memory: 750Mi
        limits:
          cpu: 2000m
          memory: 2Gi
    postgresql:
      enabled: true
      auth:
        existingSecret: "authentik-postgres-secrets"
      primary:
        persistence:
          enabled: true
          storageClass: "ceph-block-internal"
          size: 8Gi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    redis:
      enabled: true
      master:
        persistence:
          enabled: true
          storageClass: "ceph-block-internal"
          size: 8Gi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

  valuesFrom:
    - targetPath: authentik.postgresql.password
      kind: Secret
      name: authentik-postgres-secrets
      valuesKey: password
    - targetPath: authentik.secret_key
      kind: Secret
      name: authentik-sub-secrets
      valuesKey: AUTHENTIK_SECRET_KEY
    - targetPath: authentik.email.host
      kind: Secret
      name: authentik-sub-secrets
      valuesKey: AUTHENTIK_EMAIL_HOST
    - targetPath: authentik.email.port
      kind: Secret
      name: authentik-sub-secrets
      valuesKey: AUTHENTIK_EMAIL_PORT
    - targetPath: authentik.email.username
      kind: Secret
      name: authentik-sub-secrets
      valuesKey: AUTHENTIK_EMAIL_USERNAME
    - targetPath: authentik.email.password
      kind: Secret
      name: authentik-sub-secrets
      valuesKey: AUTHENTIK_EMAIL_PASSWORD
    - targetPath: authentik.email.from
      kind: Secret
      name: authentik-sub-secrets
      valuesKey: AUTHENTIK_EMAIL_FROM
