---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./outpost-ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
