---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
configMapGenerator:
  - name: authentik-assets-custom-css
    files:
      - assets/custom.css
  - name: authentik-assets-flow-background-jpg
    files:
      - assets/flow_background.jpg
  - name: authentik-assets-theme-dark-css
    files:
      - assets/theme-dark.css
  - name: authentik-assets-icon-left-brand
    files:
      - assets/icon_left_brand.svg
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
