---
global:
  envFrom:
    - secretRef:
        name: authentik-env-secrets
authentik:
  error_reporting:
    enabled: false
    send_pii: false
    environment: "nanabooboo"
  postgresql:
    enabled: true
server:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 1
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Networking
      gethomepage.dev/name: Authentik
      gethomepage.dev/icon: authentik.png
      gethomepage.dev/pod-selector: app.kubernetes.io/name=authentik
      gethomepage.dev/widget.type: authentik
      gethomepage.dev/widget.url: http://authentik-server.networking.svc.cluster.local
      gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
      external-dns.alpha.kubernetes.io/hostname: "ipv4.${SECRET_DOMAIN}"
    hosts: &hosts
      - "auth.${SECRET_DOMAIN}"
    tls:
      - hosts: *hosts

worker:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 1

postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-postgres-secrets"
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block-internal"
      size: 8Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: "ceph-block-internal"
      size: 8Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
