---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: littlelink
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      littlelink:
        replicas: 2
        strategy: RollingUpdate
        containers:
          littlelink:
            image:
              repository: ghcr.io/techno-tim/littlelink-server
              tag: latest@sha256:9b7a42bb370fb0c9fd1cc55627c6d08535d7c2aa75436b2feb9d25e44ec0e504
              pullPolicy: Always

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            env:
              TZ: "${TIMEZONE}"
              META_TITLE: Spencer Callicott
              META_DESCRIPTION: Spencer Callicott (Tuxprogrammer)
              META_AUTHOR: Spencer Callicott
              THEME: Dark
              FAVICON_URL: https://avatars.githubusercontent.com/u/8989940
              AVATAR_URL: https://avatars.githubusercontent.com/u/8989940
              AVATAR_2X_URL: https://avatars.githubusercontent.com/u/8989940
              AVATAR_ALT: Spencer Callicott
              NAME: Spencer Callicott
              BIO: "i like computers"
              BUTTON_ORDER: DISCORD,STEAM,YOUTUBE,FACEBOOK,INSTAGRAM,TWITTER,LINKED_IN,GITHUB,GITLAB,EMAIL
              DISCORD: https://discord.com/users/204414182886473737
              STEAM: https://steamcommunity.com/id/tuxp
              YOUTUBE: https://www.youtube.com/channel/UC2WA4RMrvZosm7xRLnhTPBA
              FACEBOOK: https://www.facebook.com/b1nary.v01d
              INSTAGRAM: https://www.instagram.com/spencer.callicott/
              TWITTER: https://twitter.com/@whizkid1111
              LINKED_IN: https://www.linkedin.com/in/spencercallicott/
              GITHUB: https://github.com/Tuxprogrammer
              GITLAB: https://gitlab.com/tuxprogrammer
              EMAIL: spencer@tuxhpc.net
              EMAIL_TEXT: Email
              # CUSTOM_BUTTON_ALT_TEXT: Donation link,Website link
              # CUSTOM_BUTTON_ICON: fas fa-donate,fa-solid fa-globe
              # CUSTOM_BUTTON_NAME: Donate,Website
              # CUSTOM_BUTTON_COLOR: "#ffffff,#ffffff"
              # CUSTOM_BUTTON_TEXT: Buy me a coffee,Main website
              # CUSTOM_BUTTON_TEXT_COLOR: "#ED2756,#00000"
              # CUSTOM_BUTTON_URL: https://www.buymeacoffee.com/skykrypt,https://skym.fi
              # BUTTON_TARGET: _blank
              FOOTER: BOTTOM TEXT

            resources:
              requests:
                memory: 64M
              limits:
                memory: 95M
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    service:
      littlelink:
        controller: littlelink
        ports:
          http:
            port: *port

    ingress:
      littlelink:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Self-hosted Linktree Socials
          gethomepage.dev/group: Services
          gethomepage.dev/icon: littlelink-custom
          gethomepage.dev/name: Littlelink
          gethomepage.dev/siteMonitor: "http://littlelink.default.svc.cluster.local:3000"
        hosts:
          - host: &host "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: littlelink
                  port: 3000
        tls:
          - hosts:
              - *host
