---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: cronjob

        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@hourly"

        pod:
          restartPolicy: OnFailure

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/kubernetes-kubectl
              tag: 1.29.0@sha256:e7705753c1a0b8c47e50a045f6aef50415949771be110adcfb137b33609c2921
            command: ["/bin/bash", "/app/cloudflare-ddns.sh"]
            envFrom:
              - secretRef:
                  name: cloudflare-ddns-secret
    service:
      main:
        enabled: false

    persistence:
      script:
        name: cloudflare-ddns-configmap
        type: configMap
        defaultMode: 0775
        globalMounts:
          - path: /app/cloudflare-ddns.sh
            subPath: cloudflare-ddns.sh
            readOnly: true
