apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "bitwarden-${SECRET_DOMAIN_2/./-}-production"
  namespace: default
spec:
  secretName: "bitwarden-${SECRET_DOMAIN_2/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bitwarden.${SECRET_DOMAIN_2}"
  dnsNames:
    - "bitwarden.${SECRET_DOMAIN_2}"
