---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cert-manager
      namespace: cert-manager
    - name: ingress-nginx
      namespace: networking
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vaultwarden:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: vaultwarden/server
              tag: 1.33.2@sha256:87edb99945da91bd7504ac1435495595af2e89ad2c7adc151ae5bf091ec8baf2
            env:
              DOMAIN: "https://bitwarden.${SECRET_DOMAIN_2}"
              DATA_FOLDER: data
              ATTACHMENTS_FOLDER: data/attachments
              ICON_CACHE_FOLDER: data/icon_cache
              TZ:
              WEBSOCKET_ADDRESS: 0.0.0.0
              WEBSOCKET_ENABLED: "true"
              WEBSOCKET_PORT: 3012
              SIGNUPS_ALLOWED: "false"
              SMTP_ACCEPT_INVALID_CERTS: true
              SMTP_ACCEPT_INVALID_HOSTNAMES: true
            envFrom:
              - secretRef:
                  name: vaultwarden
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 100Mi
    service:
      app:
        enabled: true
        controller: vaultwarden
        ports:
          http:
            port: *port
          websocket:
            port: &ws-port 3012

    ingress:
      app:
        className: nginx
        annotations:
          # disabled for 40x because it is used for the API
          nginx.ingress.kubernetes.io/custom-http-errors: 500,501,502,503,504,505,506,510
          external-dns.home.arpa/enabled: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Bitwarden
          gethomepage.dev/icon: bitwarden.png
          gethomepage.dev/description: Bitwarden Password Manager
          gethomepage.dev/group: Networking
        hosts:
          - host: &host "bitwarden.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: vaultwarden
                  port: *port
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  name: vaultwarden
                  port: *port
              - path: /notifications/hub
                pathType: Prefix
                service:
                  name: vaultwarden
                  port: *ws-port
        tls:
          - hosts:
              - *host
            secretName: "bitwarden-${SECRET_DOMAIN_2/./-}-production-tls"
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /data
