---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    controllers:
      vaultwarden:
        strategy: Recreate

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.6
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: vaultwarden-postgres
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

        containers:
          vaultwarden:
            image:
              repository: vaultwarden/server
              tag: 1.33.1

            env:
              ATTACHMENTS_FOLDER: data/attachments
              DATA_FOLDER: data
              DOMAIN: "https://bitwarden.${SECRET_DOMAIN_2}"
              ICON_CACHE_FOLDER: data/icon_cache
              TZ: ${TIMEZONE}
              WEBSOCKET_ADDRESS: 0.0.0.0
              WEBSOCKET_ENABLED: "true"
              WEBSOCKET_PORT: 3012

            envFrom:
              - secretRef:
                  name: vaultwarden-postgres

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 100Mi

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    service:
      vaultwarden:
        ports:
          http:
            port: *port
          websocket:
            enabled: true
            port: 3012

    ingress:
      vaultwarden:
        enabled: true
        className: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: Security
          hajimari.io/icon: "simple-icons:vaultwarden"
          hajimari.io/appName: Vaultwarden
          hajimari.io/info: Password Manager
        hosts:
          - host: &host "bitwarden.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /notifications/hub
                pathType: Prefix
                service:
                  name: main
                  port: websocket
        tls:
          - hosts:
              - *host
            secretName: "bitwarden-${SECRET_DOMAIN_2/./-}-production-tls"

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /data
