---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: vaultwarden/server
      tag: 1.27.0
    env:
      DATA_FOLDER: "data"
      ICON_CACHE_FOLDER: "data/icon_cache"
      ATTACHMENTS_FOLDER: "data/attachments"
      DOMAIN: "https://bitwarden.${SECRET_DOMAIN_2}"
      TZ: "${TIMEZONE}"
      WEBSOCKET_ENABLED: "true"
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012
    persistence:
      data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /data
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:lock
        hosts:
          - host: &host "bitwarden.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: *websocket-port
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 2Gi
