---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: ingress-nginx
      namespace: networking
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.26.1@sha256:bca4407f1f3ecb2e02bd57f704593c64f89bbf3fad53f03ebcf4baecb0122de6
            env:
              TZ: ${TIMEZONE}
              DOMAIN: https://freshrss.${SECRET_DOMAIN}
              CRON_MIN: "*/15"
              OIDC_ENABLED: "1"
              OIDC_PROVIDER_METADATA_URL: https://auth.${SECRET_DOMAIN}/application/o/freshrss/.well-known/openid-configuration
              OIDC_REMOTE_USER_CLAIM: preferred_username
              OIDC_SCOPES: openid profile
              OIDC_X_FORWARDED_HEADERS: X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
            envFrom:
              - secretRef:
                  name: freshrss-secrets
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 300Mi
              requests:
                cpu: 10m
                memory: 100Mi
    service:
      app:
        enabled: true
        controller: freshrss
        ports:
          http:
            port: &port 80

    ingress:
      app:
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Updates
          gethomepage.dev/description: FreshRSS Feed Aggregator
          gethomepage.dev/icon: freshrss.png
          gethomepage.dev/name: FreshRSS
          gethomepage.dev/siteMonitor: "http://freshrss.default.svc.cluster.local:80"
          gethomepage.dev/widget.type: freshrss
          gethomepage.dev/widget.url: "http://freshrss.default.svc.cluster.local:80"
          gethomepage.dev/widget.username: "{{`{{HOMEPAGE_VAR_FRESHRSS_USERNAME}}`}}"
          gethomepage.dev/widget.password: "{{`{{HOMEPAGE_VAR_FRESHRSS_PASSWORD}}`}}"
        hosts:
          - host: &host "freshrss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: freshrss
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /var/www/FreshRSS/data
