---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-elk-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/monitoring/elk/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: elk-elasticsearch-master-tls
      namespace: monitoring
    - apiVersion: v1
      kind: Secret
      name: elk-elasticsearch-data-tls
      namespace: monitoring
    - apiVersion: v1
      kind: Secret
      name: elk-elasticsearch-ingest-tls
      namespace: monitoring
    - apiVersion: v1
      kind: Secret
      name: elk-elasticsearch-coordinating-tls
      namespace: monitoring
  interval: 10m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-elk
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-elk-certs
  path: ./kubernetes/apps/monitoring/elk/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: elk
      namespace: monitoring
  interval: 10m
  retryInterval: 1m
  timeout: 5m
