---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-istio-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
  path: ./common/istio-1-22/istio-crds/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workloadgroups.networking.istio.io
  interval: 20m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-istio-namespace
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    - name: kubeflow-istio-crds
  path: ./common/istio-1-22/istio-namespace/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: v1
      kind: Namespace
      name: istio-system
  interval: 20m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-istio
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    - name: kubeflow-istio-crds
    - name: kubeflow-istio-namespace
  path: ./common/istio-1-22/istio-install/overlays/oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
  interval: 20m
  retryInterval: 1m
  timeout: 3m
