---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  chart:
    spec:
      chart: harbor
      version: 19.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: harbor
  targetNamespace: default
  interval: 20m0s
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 15m
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
    - targetPath: adminPassword
      kind: Secret
      name: harbor-secrets
      valuesKey: HARBOR_ADMIN_PASSWORD
    - targetPath: registry.credentials.password
      kind: Secret
      name: harbor-secrets
      valuesKey: REGISTRY_CREDENTIAL_PASSWORD
    - targetPath: registry.credentials.htpasswd
      kind: Secret
      name: harbor-secrets
      valuesKey: REGISTRY_CREDENTIAL_HTPASSWD
    - targetPath: postgresql.auth.postgresPassword
      kind: Secret
      name: harbor-secrets
      valuesKey: POSTGRESQL_PASSWORD
    - targetPath: redis.auth.password
      kind: Secret
      name: harbor-secrets
      valuesKey: REGISTRY_REDIS_PASSWORD
