---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/networking/authentik/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: authentik-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: authentik
      namespace: networking
  interval: 20m
  retryInterval: 1m
  timeout: 5m
