---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elk
  namespace: monitoring
spec:
  chart:
    spec:
      chart: elasticsearch
      version: 19.21.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: elk
  targetNamespace: monitoring
  interval: 20m0s
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 60m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 60m
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: elk-values
