---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: elk-values
    files:
      - values.yaml
resources:
  - ./secrets.sops.yml
  # - ./helmrelease.yaml
  - ./elastic-agent-standalone.yaml
labels:
  - pairs:
      app.kubernetes.io/name: elk
      app.kubernetes.io/instance: elk
