---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "arrstack-${SECRET_DOMAIN_2/./-}-production"
  namespace: networking
spec:
  secretName: "arrstack-${SECRET_DOMAIN_2/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "media-services.${SECRET_DOMAIN_2}"
  dnsNames:
    - "media-services.${SECRET_DOMAIN_2}"
    # - "plex.${SECRET_DOMAIN_2}"
    - "jellyseerr.${SECRET_DOMAIN_2}"
    - "desktop.${SECRET_DOMAIN_2}"
    # - "plex.${SECRET_DOMAIN}"
    - "jellyseerr.${SECRET_DOMAIN}"
    - "desktop.${SECRET_DOMAIN}"
