---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "nextcloud-${SECRET_DOMAIN_2/./-}-production"
  namespace: networking
spec:
  secretName: "nextcloud-${SECRET_DOMAIN_2/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "nextcloud.${SECRET_DOMAIN_2}"
  dnsNames:
    - "nextcloud.${SECRET_DOMAIN_2}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "office-${SECRET_DOMAIN_2/./-}-production"
  namespace: networking
spec:
  secretName: "office-${SECRET_DOMAIN_2/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "office.${SECRET_DOMAIN_2}"
  dnsNames:
    - "office.${SECRET_DOMAIN_2}"
