---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubeflow-manifests
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/Tuxprogrammer/kubeflow-manifests
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/example
    !/apps
    !/common
