---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubeflow-manifests
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubeflow/manifests
  ref:
    tag: v1.7.0
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/apps
    !/common
