---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeflow-manifests
  namespace: flux-system
spec:
  interval: 20m
  url: https://github.com/Tuxprogrammer/kubeflow-manifests
  ref:
    branch: v1.9.1-branch
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/example
    !/apps
    !/common
    !/contrib
