apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: webhook-namecheap
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Extrality/cert-manager-webhook-namecheap
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
