---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-recyclarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  path: ./kubernetes/apps/media/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: recyclarr
      namespace: media
  interval: 20m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      # Defaults
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      # minecraft specific
      - kind: Secret
        name: recyclarr-pre-secret
