---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./nfs-mounts.yaml
  # Arrstack
  - ./calibre-web-automated/ks.yaml
  - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-chan/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-chan/ks.yaml
  # - ./plex/ks.yaml
