---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-store0
  namespace: media
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: store.${SECRET_DOMAIN_2}
    path: "/mnt/store0/linux"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-store0
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  volumeName: media-store0
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-archive0
  namespace: media
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: archive.${SECRET_DOMAIN_2}
    path: "/mnt/archive0/linux"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-archive0
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  volumeName: media-archive0
  resources:
    requests:
      storage: 1Mi
