---
# CN = redis
# DNS:*.redis.default.svc.cluster.local
# DNS:redis.default.svc.cluster.local
# DNS:redis
# DNS:127.0.0.1
# DNS:localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-cert
  namespace: default
spec:
  secretName: redis-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: redis
  dnsNames:
    - "*.redis.default.svc.cluster.local"
    - redis.default.svc.cluster.local
    - redis
    - "127.0.0.1"
    - localhost
