---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: 9.0.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.1@sha256:b9735c9d08c3244c462bb81263ff5f4ad4e24b96865338c14733a59e3624dfaf
        volumeMounts:
          - mountPath: /target
            name: plugins
    containerSecurityContext:
      runAsUser: 0
      runAsNonRoot: false
      privileged: true
    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: k8s-backups
          prefix: velero
          caCert: ""
          config:
            region: minio
            s3Url: https://store.tuxhpc.net:9000
            s3ForcePathStyle: true
            insecureSkipTLSVerify: true
      extraEnvVars:
        TZ: America/Chicago
      defaultVolumesToFsBackup: true
    credentials:
      existingSecret: velero-secrets
    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    nodeAgent:
      containerSecurityContext:
        runAsUser: 0
        runAsNonRoot: false
        privileged: true
    schedules:
      weekly:
        schedule: "0 3 * * 0"
        template:
          includedNamespaces:
            - "*"
          ttl: 720h # 30 days
      daily:
        schedule: "0 3 * * 1-6"
        template:
          includedNamespaces:
            - "*"
          ttl: 180h # 7 days
      hourly:
        schedule: "0 0-2,4-23 * * *"
        template:
          includedNamespaces:
            - "*"
          ttl: 24h # 1 days
          defaultVolumesToFsBackup: false # don't backup pod filesystems for the hourly schedule
  valuesFrom:
    - targetPath: configuration.backupStorageLocation[0].caCert
      kind: Secret
      name: velero-secrets
      valuesKey: caCert
