---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:latest
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      backupStorageLocation:
        - name: archive
          provider: aws
          bucket: k8s-backups
          prefix: velero
          config:
            region: minio
            s3Url: https://archive.tuxhpc.net:9000
            s3ForcePathStyle: true
      uploaderType: restic
      extraEnvVars:
        TZ: America/Chicago
    credentials:
      existingSecret: velero-secrets
    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    schedules:
      weekly:
        schedule: "0 3 * * 0"
        template:
          includedNamespaces:
            - "*"
