---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: velero
