---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyseerr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: radarr
      namespace: media
    - name: radarr-chan
      namespace: media
    - name: sonarr
      namespace: media
    - name: sonarr-chan
      namespace: media
  interval: 15m
  values:
    controllers:
      *app :
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
          backup.velero.io/backup-volumes-excludes: media-archive0,media-store0
        containers:
          *app :
            image:
              repository: ghcr.io/fallenbagel/jellyseerr
              tag: 2.3.0@sha256:df53a7b06006e9da117a7072a55cf5d8b2071a6272f6bb329d8ca62b6f5c08a6
            env:
              LOG_LEVEL: info
              TZ: ${TIMEZONE}
              PORT: &port 5055
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 5m
                memory: 350Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      *app :
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "{{ title .Release.Namespace }}"
          gethomepage.dev/name: "{{ title .Release.Name }}"
          gethomepage.dev/icon: "{{ .Release.Name }}"
          gethomepage.dev/description: "Media Request Management"
          gethomepage.dev/siteMonitor: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.type: "{{ .Release.Name }}"
          gethomepage.dev/widget.url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_JELLYSEERR_TOKEN}}`}}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: *app
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block-internal
        advancedMounts:
          *app :
            *app :
              - path: /app/config
      logs:
        type: emptyDir
        advancedMounts:
          *app :
            *app :
              - path: /app/config/logs
      tmp:
        type: emptyDir
        advancedMounts:
          *app :
            *app :
              - path: /tmp
