---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configMapGenerator:
  - name: influxdb-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/instance: influxdb
