apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secrets
    namespace: default
stringData:
    admin-user-password: ENC[AES256_GCM,data:4o+GpSuxNxO032oWFGm5j2ZpEFLavd/vby/2vHl+Hn4=,iv:l7AT/DMY+ixVRVVVkcw7ufzh1HhFBXnscv1kckONRTg=,tag:awNR2dY1fD6h3e9+yxpX/g==,type:str]
    admin-user-token: ENC[AES256_GCM,data:tVm7cW/RZRL4KQNlsIFE/Q1VRv3VmsfAoxGmdg+mF70=,iv:CjMiAK1W6/zpddHzxQJrP4qcXWbT61OJcx/DYDRHjWs=,tag:W2WAKgvm1yjy+BM/mts1EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVGxWUDhlNWxHeFlIN0kv
            ZVRRRlBqNExmV05qQ2x4RHh6RW1QbW9ZWkRrCkJDTkltVG1MV0VwRDZ0QmdTMFlU
            RTJhRHJVcExiWERUcGRaN1MxNGxQS0kKLS0tIE00T21CSmtMUWxXUUdLTWlHSStr
            eGhRT0NPd0ZwVk5kTUYxVFUrUjdDaTQKDEl6IBdxzQ4i+9zi9+4r/T3jWVby3XpY
            T0pPkdt8xpY6Uvvc3GetbgM4Ly4/WupyxmLp05GPauuIDcSwqRJyUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T08:26:28Z"
    mac: ENC[AES256_GCM,data:57tNYxdELkQvZgr53/zoLC29bBVMYhl1bO2cV4AObkF0tHiKVxAJbPYaQKRirRPjhuWBsdfddCIw4lkZv6X+mFLD4bAlivlQsdGUm3cjeonrkQA7Lsqc+Y+9cju8KG3Z6iwqHgC3tC6SyCJP5vg1EQEiUi+IxEdH1aqiO14oi/c=,iv:GMuVvp/avftZNGrUQBNb0M5aZ0rJPKzMgeWn5SNs06g=,tag:Tss3TJECdDuRDUQg9QuIhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
