---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: arrstack
      app.kubernetes.io/instance: arrstack
generatorOptions:
  disableNameSuffixHash: true
