---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-cloudnative-pg-cluster
  path: ./kubernetes/apps/default/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vaultwarden
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 3m
