---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 20m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 20m
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-values
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: nextcloud-metrics
            patch: |
              # Fix the securityContext for nextcloud-metrics pod
              - op: add
                path: /spec/template/spec/securityContext
                value:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
              # Fix the securityContext for nextcloud-metrics container 0
              - op: add
                path: /spec/template/spec/containers/0/securityContext
                value:
                  runAsUser: 1000
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
