---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 4.3.6
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 20m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 20m
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-values
