---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configMapGenerator:
  - name: nextcloud-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - secret.sops.yaml
  - nfs-pvc.yaml
  - helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
