---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: archive.${SECRET_DOMAIN_2}
    path: /mnt/archive0/nextcloud
  # Note: The first two options are strictly for NFSv3
  mountOptions: ["nfsvers=3", "nconnect=16", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: manual
  resources:
    requests:
      storage: 1Mi
