---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./harbor.yaml
labels:
  - pairs:
      app.kubernetes.io/name: harbor
      app.kubernetes.io/instance: harbor
