---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/Tuxprogrammer/kubeflow-manifests.git/common/oauth2-proxy/overlays/m2m-dex-only/?ref=v1.9.1-branch
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: ./config/oauth2-proxy.yaml
    target:
      kind: ConfigMap
      name: oauth2-proxy
      namespace: oauth2-proxy
  - path: ./secret/oauth2-proxy.sops.yaml
    target:
      kind: Secret
      name: oauth2-proxy
      namespace: oauth2-proxy
