apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: authentik-jwt
  namespace: istio-system
spec:
  jwtRules:
    - forwardOriginalToken: true
      fromHeaders:
        - name: Authorization
          prefix: 'Bearer '
      issuer: http://authentik-server.networking.svc.cluster.local:80/application/o/kubeflow/
      outputClaimToHeaders:
        - claim: email
          header: kubeflow-userid
        - claim: groups
          header: kubeflow-groups
  selector:
    matchLabels:
      app: istio-ingressgateway
