---
kubernetes:
  children:
    master:
      hosts:
        k8s-m1:
          ansible_host: 10.2.0.10
        k8s-m2:
          ansible_host: 10.2.0.20
        k8s-m3:
          ansible_host: 10.2.0.30
    worker:
      vars:
        rook_block_device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
      hosts:
        k8s-w81:
          ansible_host: 10.2.0.81
        k8s-w11:
          ansible_host: 10.2.0.11
        k8s-w21:
          ansible_host: 10.2.0.21
        k8s-w31:
          ansible_host: 10.2.0.31
        k8s-w41:
          ansible_host: 10.2.0.41
        k8s-w51:
          ansible_host: 10.2.0.51
        k8s-w61:
          ansible_host: 10.2.0.61
        k8s-w71:
          ansible_host: 10.2.0.71
