---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-system-upgrade-controller
  namespace: flux-system
spec:
  path: ./kubernetes/apps/system-upgrade/system-upgrade-controller/app
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: system-upgrade-controller
      namespace: system-upgrade
  interval: 20m
  retryInterval: 1m
  timeout: 3m
