---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/objectbucketclaim_v1alpha1.json
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: pg-backups
  namespace: default
spec:
  bucketName: pg-backups
  storageClassName: ceph-bucket-internal
