---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 15m
  values:
    controllers:
      *app :
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
          backup.velero.io/backup-volumes-excludes: media-archive0,media-store0
        initContainers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
              pullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              HEALTH_VPN_DURATION_INITIAL: 120s
              HEALTH_SUCCESS_WAIT_DURATION: 120s
              HEALTH_SERVER_ADDRESS: :9999
              FIREWALL_INPUT_PORTS: 8080,9999
              FIREWALL_OUTBOUND_SUBNETS: ${CLUSTER_CIDR},${SERVICE_CIDR}
              DOT: "off"
              DNS_ADDRESS: 10.0.0.243
              PORT_FORWARD_ONLY: "true"
              OPENVPN_PROTOCOL: udp
              VPN_SERVICE_PROVIDER: "private internet access"
              VPN_PORT_FORWARDING: "on"
              VPN_PORT_FORWARDING_STATUS_FILE: /gluetun/forwarded_port
              VPN_PORT_FORWARDING_UP_COMMAND: |
                /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{`{{PORTS}}`}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
            envFrom:
              - secretRef:
                  name: qbittorrent-secrets
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
                squat.ai/tun: "1"
              limits:
                memory: 512Mi
                squat.ai/tun: "1"
            securityContext:
              privileged: true
              runAsUser: 0
              runAsGroup: 0
              capabilities:
                add:
                  - NET_RAW
                  - NET_ADMIN
                  - SYS_MODULE
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  exec: &exec
                    command: [/gluetun-entrypoint, healthcheck]
                  periodSeconds: 60
              startup:
                <<: *probe
                spec:
                  exec: *exec
                  periodSeconds: 30
        containers:
          *app :
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.4@sha256:17e3e5f1c7e7fe81434f9d1f5f2e00da9a67f6dbfda1c988c0619932cb856047
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: &port 8080
                  initialDelaySeconds: 0
                  timeoutSeconds: 10
                  periodSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2048Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          vuetorrent:
            dependsOn: *app
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.4.0@sha256:0330739a707a2969d617e859f096659ab6d149212658ac0ad7e550b59482ebf0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          *app :
            *app :
              - path: /config
      gluetun:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          *app :
            gluetun:
              - path: /gluetun
      media:
        existingClaim: media-archive0
        advancedMounts:
          *app :
            *app :
              - path: /downloads
                subPath: plex/qbittorrent
      inprogress:
        retain: false
        accessMode: ReadWriteOnce
        storageClass: ceph-block-internal-fast
        size: 400Gi
        advancedMounts:
          *app :
            *app :
              - path: /downloads/InProgress
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      *app :
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.networking.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "{{ title .Release.Namespace }}"
          gethomepage.dev/name: "{{ title .Release.Name }}"
          gethomepage.dev/icon: "{{ .Release.Name }}"
          gethomepage.dev/description: "Bittorrent Download Agent"
          gethomepage.dev/siteMonitor: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.type: "{{ .Release.Name }}"
          gethomepage.dev/widget.url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}` }}"
        hosts:
          - host: qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: *app
                  port: http
        tls:
          - hosts:
              - qbittorrent.${SECRET_DOMAIN}
            secretName: "{{ .Release.Name }}-${SECRET_DOMAIN/./-}-production-tls"
