---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 15m
  values:
    controllers:
      *app :
        type: statefulset
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
            backup.velero.io/backup-volumes-excludes: media,inprogress,addons,tmp
          nodeSelector:
            good-for-bittorrent: "true"
        initContainers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
              pullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              HEALTH_VPN_DURATION_INITIAL: 120s
              HEALTH_SUCCESS_WAIT_DURATION: 120s
              HEALTH_SERVER_ADDRESS: :9999
              FIREWALL_INPUT_PORTS: 8080,9999,62257
              FIREWALL_OUTBOUND_SUBNETS: ${CLUSTER_CIDR},${SERVICE_CIDR}
              DOT: "off"
              DNS_ADDRESS: 10.128.0.1
              VPN_SERVICE_PROVIDER: "airvpn"
              VPN_TYPE: "wireguard"
            envFrom:
              - secretRef:
                  name: qbittorrent-secrets
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
                squat.ai/tun: "1"
              limits:
                squat.ai/tun: "1"
            securityContext:
              privileged: true
              runAsUser: 0
              runAsGroup: 0
              capabilities:
                add:
                  - NET_RAW
                  - NET_ADMIN
                  - SYS_MODULE
              sysctls:
                - name: net.ipv6.conf.all.disable_ipv6
                  value: "1"
                - name: net.ipv6.conf.default.disable_ipv6
                  value: "1"
                - name: net.ipv6.conf.lo.disable_ipv6
                  value: "1"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  exec: &exec
                    command: [/gluetun-entrypoint, healthcheck]
                  periodSeconds: 60
              startup:
                <<: *probe
                spec:
                  exec: *exec
                  periodSeconds: 30
        containers:
          *app :
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: &port 8080
                  initialDelaySeconds: 0
                  timeoutSeconds: 10
                  periodSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          vuetorrent:
            dependsOn: *app
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.4.2@sha256:3089d9787b89bdc5af01d9f6e8d515aefb9672e8aea3972d7ff67478112bacb3
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      vpn-shuffle:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
          backoffLimit: 2
          activeDeadlineSeconds: 600
        containers:
          *app :
            image:
              repository: bitnami/kubectl
              tag: 1.33@sha256:ed0b31a0508da84ee655c5c6e01bd3897fc56ad6cf69debb27fa1893a06d2246
            command:
              - bash
              - -c
              - >-
                kubectl rollout restart statefulset/qbittorrent &&
                kubectl rollout status statefulset/qbittorrent
            resources:
              requests:
                cpu: 5m
                memory: 36M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          *app :
            *app :
              - path: /config
      media:
        existingClaim: media-archive0
        advancedMounts:
          *app :
            *app :
              - path: /downloads
                subPath: plex/qbittorrent
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      *app :
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.networking.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "{{ title .Release.Namespace }}"
          gethomepage.dev/name: "{{ title .Release.Name }}"
          gethomepage.dev/icon: "{{ .Release.Name }}"
          gethomepage.dev/description: "Bittorrent Download Agent"
          gethomepage.dev/siteMonitor: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.type: "{{ .Release.Name }}"
          gethomepage.dev/widget.url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}` }}"
        hosts:
          - host: qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: *app
                  port: http
        tls:
          - hosts:
              - qbittorrent.${SECRET_DOMAIN}
            secretName: "{{ .Release.Name }}-${SECRET_DOMAIN/./-}-production-tls"
