---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./network-policy.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./loki/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
