---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mongodb-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/default/mongodb/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: mongodb-0-tls
      namespace: default
    - apiVersion: v1
      kind: Secret
      name: mongodb-1-tls
      namespace: default
    - apiVersion: v1
      kind: Secret
      name: mongodb-2-tls
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mongodb
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-mongodb-certs
  path: ./kubernetes/apps/default/mongodb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mongodb
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 5m
