---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
configMapGenerator:
  - name: bedrock-vanilla-values
    files:
      - values.yaml
resources:
  - helmrelease.yaml
configurations:
  - kustomizeconfig.yaml
