---
- Communicate:
    - Discord:
        - icon: discord.png
          href: "https://discord.com/app"
          target: _self
    - Gmail:
        - icon: gmail.png
          href: "http://gmail.com"
          target: _self
    - Google Calendar:
        - icon: google-calendar.png
          href: "https://calendar.google.com"
          target: _self
- Media:
    - YouTube:
        - icon: youtube.png
          href: "https://youtube.com/feed/subscriptions"
          target: _self
- Gaming:
    - World of Tanks:
        - icon: https://eu-wotp.wgcdn.co/dcont/fb/image/world_of_tanks_logo_png_440x440.png
          href: "https://worldoftanks.com"
          target: _self
    - Skill4LTU:
        - icon: https://skill4ltu.eu/images/skill4ltu-logo-icon.png
          href: "https://skill4ltu.eu"
          target: _self
    - Tanks.gg:
        - icon: https://tanks.gg/img/icons/regions/wg-only.png
          href: "https://tanks.gg"
          target: _self
- Reading:
    - Reddit:
        - icon: reddit.png
          href: "https://reddit.com"
          target: _self
- Git:
    - kubesearch:
        - icon: kubernetes-dashboard.png
          href: "https://kubesearch.dev/"
          target: _self
    - homelab:
        - icon: github.png
          href: "https://github.com/tuxprogrammer/homelab"
          target: _self
    - containers:
        - icon: docker.png
          href: "https://hub.docker.com"
          target: _self
    - onedr0p-home-ops:
        - icon: github.png
          href: "https://github.com/onedr0p/home-ops"
          target: _self
    - bjw-s-home-ops:
        - icon: github.png
          href: "https://github.com/bjw-s/home-ops"
          target: _self
    - bjw-s-helm-charts:
        - icon: github.png
          href: "https://github.com/bjw-s/helm-charts"
          target: _self
- Work:
    - te:
        - icon: https://play-lh.googleusercontent.com/DJntClnN5bSV9XAqvY6ZOS2-jvvWIVRXHWtu2bp3psWZ3a6i62LvRV0N4mby0H6Qu6LH
          href: "https://te.{{HOMEPAGE_VAR_WORK_DOMAIN}}"
          target: _self
    - portal:
        - icon: https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/assets/brand-icons/product/png/outlook_96x1.png
          href: "https://portal.office365.us"
          target: _self
    - teams:
        - icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg/2203px-Microsoft_Office_Teams_%282018%E2%80%93present%29.svg.png
          href: "https://gov.teams.microsoft.us.mcas-gov.us/v2"
          target: _self
    - prism:
        - icon: https://companieslogo.com/img/orig/LDOS-9dbc97eb.png?t=1720244492
          href: "https://prism.{{HOMEPAGE_VAR_WORK_DOMAIN}}"
          target: _self
    - desktop:
        - icon: https://static-00.iconduck.com/assets.00/citrix-receiver-icon-2048x2045-6si6dssr.png
          href: "https://desktop.{{HOMEPAGE_VAR_WORK_DOMAIN}}"
          target: _self
