---
- Network:
    - OPNSense:
        href: https://gw.${SECRET_DOMAIN_2}
        target: _self
        icon: opnsense
        description: OPNSense
        widget:
          type: opnsense
          url: https://10.0.0.1
          username: "{{HOMEPAGE_VAR_OPNSENSE_USERNAME}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_PASSWORD}}"
          wan: wan
- Infrastructure:
    - Archive:
        href: https://archive.${SECRET_DOMAIN_2}
        target: _self
        icon: truenas.png
        description: TrueNAS Scale
        widget:
          type: truenas
          url: https://archive.${SECRET_DOMAIN_2}
          key: "{{HOMEPAGE_VAR_TRUENAS_ARCHIVE_APIKEY}}"
          enablePools: true
    - Store:
        href: https://store.${SECRET_DOMAIN_2}
        target: _self
        icon: truenas.png
        description: TrueNAS Scale
        widget:
          type: truenas
          url: https://store.${SECRET_DOMAIN_2}
          key: "{{HOMEPAGE_VAR_TRUENAS_STORE_APIKEY}}"
          enablePools: true
    - node10:
        href: https://node10.${SECRET_DOMAIN_2}:8006
        target: _self
        icon: proxmox
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node10.${SECRET_DOMAIN_2}:8006
          fields: ["vms", "resources.cpu", "resources.mem"]
          username: "{{HOMEPAGE_VAR_PROXMOX_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: node10
    - node11:
        href: https://node11.${SECRET_DOMAIN_2}:8006
        target: _self
        icon: proxmox
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node11.${SECRET_DOMAIN_2}:8006
          fields: ["vms", "resources.cpu", "resources.mem"]
          username: "{{HOMEPAGE_VAR_PROXMOX_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: node11
    - node12:
        href: https://node12.${SECRET_DOMAIN_2}:8006
        target: _self
        icon: proxmox
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node12.${SECRET_DOMAIN_2}:8006
          fields: ["vms", "resources.cpu", "resources.mem"]
          username: "{{HOMEPAGE_VAR_PROXMOX_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: node12
    - node13:
        href: https://node13.${SECRET_DOMAIN_2}:8006
        target: _self
        icon: proxmox
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node13.${SECRET_DOMAIN_2}:8006
          fields: ["vms", "resources.cpu", "resources.mem"]
          username: "{{HOMEPAGE_VAR_PROXMOX_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: node13
    - node14:
        href: https://node14.${SECRET_DOMAIN_2}:8006
        target: _self
        icon: proxmox
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node14.${SECRET_DOMAIN_2}:8006
          fields: ["vms", "resources.cpu", "resources.mem"]
          username: "{{HOMEPAGE_VAR_PROXMOX_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: node14
    - seeker:
        href: https://seeker.${SECRET_DOMAIN_2}:8006
        target: _self
        icon: proxmox
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://seeker.${SECRET_DOMAIN_2}:8006
          fields: ["vms", "resources.cpu", "resources.mem"]
          username: "{{HOMEPAGE_VAR_PROXMOX_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: seeker
    - pbs:
        href: https://node10.${SECRET_DOMAIN_2}:8007
        target: _self
        icon: proxmox
        description: Backup Server for Proxmox datacenter
        widget:
          type: proxmoxbackupserver
          url: https://node10.${SECRET_DOMAIN_2}:8007
          username: "{{HOMEPAGE_VAR_PROXMOXBACKUP_API_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOXBACKUP_API_KEY}}"
          node: pbs
