---
- logo:
    icon: https://i.pinimg.com/736x/77/25/3a/77253a53ce061b5eed2e3924739ab89b.jpg
- search:
    provider: [google]
    focus: false
    target: _self
- greeting:
    text_size: xl
    text: "Hey Spencer, how are you doing today?"
- kubernetes:
    cluster:
      cpu: true
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- openmeteo:
    label: Madison
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    timezone: "{{HOMEPAGE_VAR_TIMEZONE}}"
    units: imperial
    cache: 5
    format:
      maximumFractionDigits: 1
- freshrss:
    url: "http://freshrss.default.svc.cluster.local:80"
    username: "{{HOMEPAGE_VAR_FRESHRSS_USERNAME}}"
    password: "{{HOMEPAGE_VAR_FRESHRSS_PASSWORD}}"
