apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-2
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production-2
    solvers:
      - dns01:
          webhook:
            groupName: acme.namecheap.com
            solverName: namecheap
            config:
              apiKeySecretRef:
                name: namecheap-api
                key: apiKey
              apiUserSecretRef:
                name: namecheap-api
                key: apiUser
        selector:
          dnsZones:
            - "${SECRET_DOMAIN_2}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-2
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging-2
    solvers:
      - dns01:
          webhook:
            groupName: acme.namecheap.com
            solverName: namecheap
            config:
              apiKeySecretRef:
                name: namecheap-api
                key: apiKey
              apiUserSecretRef:
                name: namecheap-api
                key: apiUser
        selector:
          dnsZones:
            - "${SECRET_DOMAIN_2}"
