apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:DymKVNxrVxQvY2avQq1mrusQ9+E1NrPfYnSCp5mc/EIQLqkTAQ==,iv:Ukv7x1cTYoKoqYYMCer4jZzY0HKim4KmOj7vJKX+1t8=,tag:HQpncpneDgfsyok8Q9GkFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUTlRbkIzdDRRZHpLa0tU
            VWZrZ2RMaXhWVU43ZndrMDgreE1lZ2x1S3dzCk5KNGFjQnIwZHAvdUdGdlRSdUV4
            K2xqd3BrcGFzNS8xOFpLZVFoWXRkU0UKLS0tIHdWR3ZVaVhsYkhzVFFCYzJJQVhr
            alpaN3Z4ZkpqTitYQmVML2FUT2Jyb2MKOjOEoDDafdqd9AR58tl/DS8vzVlv4+R9
            MDYidc6DZ33Y8U0WcVuHP3/njY3I45JKXWg8Fg8c3QEsq1p3IHHPbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T06:09:01Z"
    mac: ENC[AES256_GCM,data:aJ2xntNe66YvP08Ug0gKVDlDCbtnIoUDJGcyTyP4Rv85Nt0sBnXICXaKNjG2Fp7c4tk0tHa6t/bfzM15wJNTeX/T4/wcug1w9rFCTRSxHhFIaV0mJAKt9P7xKeIxyOhl+SU0ON3xOHWYwJIjL0eWcSFHfmtI+yfCZNIEF0tUXbM=,iv:hnThQzCNdutnLET3mQJa5zbCKf9w1C2vO7EBjFKlTMQ=,tag:ldN6nKHue78SsmNxRqSElA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
