---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-external
resources:
  - configmap/rook-ceph-mon-endpoints.yaml
  - secret/rook-ceph-mon.yaml
  # - secret/rook-csi-rbd-node.yaml
  # - secret/rook-csi-rbd-provisioner.yaml
  # - secret/rook-csi-cephfs-node.yaml
  # - secret/rook-csi-cephfs-provisioner.yaml
  # - secret/rgw-admin-ops-user.yaml
  # - storageclass/ceph-filesystem-ext.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: rook-ceph-cluster-external
      app.kubernetes.io/instance: rook-ceph-cluster-external
      app.kubernetes.io/part-of: rook-ceph-external
