---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./nfs-mounts.yaml
  # Stateless Webservers
  - ./echo-server/ks.yaml
  - ./littlelink/ks.yaml
  - ./freshrss/ks.yaml
  - ./homepage/ks.yaml
  # Databases
  - ./mosquitto/ks.yaml
  # Web Apps
  - ./home-assistant/ks.yaml
  - ./frigate/ks.yaml
  - ./vaultwarden/ks.yaml
