---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./network-policy.yaml
  # Stateless Webservers
  - ./echo-server/ks.yaml
  - ./littlelink/ks.yaml
  - ./hajimari/ks.yaml
  # Databases
  - ./cloudnative-pg/ks.yaml
  - ./mongodb/ks.yaml
  - ./mariadb/ks.yaml
  - ./redis/ks.yaml
  - ./influxdb/ks.yaml
  # Web Apps
  - ./vaultwarden/ks.yaml
  - ./harbor/ks.yaml
  - ./nextcloud/ks.yaml
