---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Stateless Webservers
  - ./echo-server/ks.yaml
  - ./littlelink/ks.yaml
  - ./hajimari/ks.yaml
  # Web Apps
  - ./vaultwarden/ks.yaml
