---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Stateless Webservers
  - ./echo-server/ks.yaml
  - ./littlelink/ks.yaml
  - ./freshrss/ks.yaml
  - ./homepage/pre-secret.sops.yaml
  - ./homepage/ks.yaml
  # Web Apps
  - ./vaultwarden/ks.yaml
  # - ./arrstack/ks.yaml
