---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre-web-automated
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 15m
  values:
    controllers:
      *app :
        type: statefulset
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
            backup.velero.io/backup-volumes-excludes: media,tmp
        containers:
          *app :
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V3.0.4@sha256:e602e73b6fd50c3ba389b38acb701205976a05b650898f615f93bd7e3537a827
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
              CACHE_DIR: /cache
              CALIBRE_PORT: &port 8083
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 45
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 5m
                memory: 350Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 1000
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
            primary: true
    ingress:
      *app :
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.networking.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "{{ title .Release.Namespace }}"
          gethomepage.dev/name: "Calibre Web"
          gethomepage.dev/icon: "calibre-web"
          gethomepage.dev/description: "Book Library Management"
          gethomepage.dev/siteMonitor: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.type: "calibreweb"
          gethomepage.dev/widget.url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.username: "{{`{{HOMEPAGE_VAR_CALIBREWEB_USERNAME}}`}}"
          gethomepage.dev/widget.password: "{{`{{HOMEPAGE_VAR_CALIBREWEB_PASSWORD}}`}}"
          gethomepage.dev/widget.enableQueue: "true"
        hosts:
          - host: &host "calibre-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: "{{ .Release.Name }}"
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: ceph-block-internal
        advancedMounts:
          *app :
            *app :
              - path: /config
      media:
        existingClaim: media-archive0
        advancedMounts:
          *app :
            *app :
              - path: /calibre-library
                subPath: shared/books
              - path: /cwa-book-ingest/manual
                subPath: shared/import
              - path: /cwa-book-ingest/nzbget
                subPath: plex/nzbget/completed/Books
      cache:
        type: emptyDir
        advancedMounts:
          *app :
            *app :
              - path: /cache
