---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-roles
  namespace: flux-system
spec:
  dependsOn:
    - name: kubeflow-oauth2-proxy
  path: ./common/kubeflow-roles/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: kubeflow-kubernetes-view
  interval: 20m
  retryInterval: 1m
  timeout: 3m
