# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster-external
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph
  path: ./kubernetes/apps/rook-ceph/rook-ceph-external/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster-external
      namespace: rook-ceph-external
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: rook-vars
        namespace: rook-ceph-external
