---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/default/redis/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: redis-tls
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-redis-certs
  path: ./kubernetes/apps/default/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 5m
