apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:uP9Nlc0fNcSX+mpiNipo5Gl2H6rBPUTXLM/v+9g+qAFoSlaTyjlkwvGne9cpYQRS9hEDiT6wpFSt7rQ3,iv:ykB0WvmaHb3YV72efa/g6PbNWhgEzLs7u1X5YrZ1BGc=,tag:83HD9fOLyyFYJaAHCKU3+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eXhWNjJXS042R3YrN3R1
            VG9qMUZMVytMNDZMcnZTM0lKdTB4WkJ2dTI4CjE3SDQvSEY4K0dvMDJWc0lCTHpT
            SWJJRW5DNHQ2Tzk1RVRKK0hTWG5xVlEKLS0tIEc1OVZ1aGRubjQ3OHpCMXo5eE9C
            STJYU0pyZjdpS2xodk54WjNQVE81dTgKf81orVMQ/xdluXHxVHstA9c+oljO2LQy
            a6zSQ+UfxXmWYOvOxzvbrYkvVnyxwh5gedO+FbTN274xErCUlNbC5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T06:27:26Z"
    mac: ENC[AES256_GCM,data:HyH/cihRKXZLtGDKqzUH5HoVjP3wcq52tiFmAa6Pt/+Qdwvi5W5i95cMrwAwiq9NBxAJu7FDXyGNURxhzOea2w+7sKi8mwB/ed0ZPV5aDYKIvWriYnc4psa31b573G5PkdNtm4tMhBIypEYaDH13LoNTy6LTcutzo585lMxNiFQ=,iv:GY47eRA1U4oyBvYUQFIzdBRfBYBAaD0FW8+QYy5VAUA=,tag:d6yrHzBscPqzGIatZ7rLgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
