apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:L2YRrod517qGxhY33uwICyg/DZt3kvRh7/4MbhPe8T59y0k2N3evv7Nn86Bevzju5AOTjMxOfb8Wd2uk,iv:JOcgUHbJvX7dPvTmHNqtZyjO83ZABVEf7hnjuzu6C6U=,tag:4hUQdPy9M2FDL5KNUUHwvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eXhWNjJXS042R3YrN3R1
            VG9qMUZMVytMNDZMcnZTM0lKdTB4WkJ2dTI4CjE3SDQvSEY4K0dvMDJWc0lCTHpT
            SWJJRW5DNHQ2Tzk1RVRKK0hTWG5xVlEKLS0tIEc1OVZ1aGRubjQ3OHpCMXo5eE9C
            STJYU0pyZjdpS2xodk54WjNQVE81dTgKf81orVMQ/xdluXHxVHstA9c+oljO2LQy
            a6zSQ+UfxXmWYOvOxzvbrYkvVnyxwh5gedO+FbTN274xErCUlNbC5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T06:12:52Z"
    mac: ENC[AES256_GCM,data:XyYjV5fHZ10acKRVdkz7mBvggmIMA0PCfG8c1HclzHnZs8NBeOfKJm0kDjC59c2PqiBMXMkKotNcwVmdb812ORo/mKAa5C5/l9AuL8hke7xiSwjS4KzWKB4Gv9D89AV3hft6iCJ9GFWihUN8dAr0b6BaOYctneQsj1pw/gTyJk4=,iv:kX9mkDihIGrQe7rWMUgUYfvv7wMLtfpnhFYoBSscdfE=,tag:/VaD1iyv4Pr9TBheqm2pkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
