---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: java-vanilla
  namespace: minecraft
spec:
  chart:
    spec:
      chart: minecraft
      version: 4.15.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  targetNamespace: minecraft
  interval: 20m0s
  valuesFrom:
    - kind: ConfigMap
      name: java-vanilla-values
