---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
configMapGenerator:
  - name: java-vanilla-values
    files:
      - values.yaml
resources:
  - discordsrv.sops.yaml
  - helmrelease.yaml
configurations:
  - kustomizeconfig.yaml
