---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-harbor-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    #- name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/default/harbor/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: harbor-tls
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-harbor
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
    #- name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-harbor-certs
  path: ./kubernetes/apps/default/harbor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: harbor
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 5m
