---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: kube-prometheus-stack
      app.kubernetes.io/instance: kube-prometheus-stack
