apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vj/zAFFUy5/hn+xEEQiLMOI=,iv:lLOTp3nIFG34FFs2WAe4bcWbgo6nDYBp8F8PxWRAnfo=,tag:OYrXd6O7YjFcG5qMb1aadQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xBUO/lq8anqE3dvIjRGPsAckIFl+0y0=,iv:vjmvVJPYz+aWLK97CepLFsparddqdLmu9vPI0cXJY3A=,tag:Swxm4K0rp42YNI8abno1lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1piekM1aEh2ekxCTUY5
            S0RBR2NWc1R0S1hSRDcwSDlnOFcrU1hEcDFrCllldXQ2Q1FDRHdmd3NJay91NFk4
            alJiQXE1WUFLQ0VtTUxPUTBwcXFZMGsKLS0tIGk4RHVFb0NKb1hqdm5kL2V3Q201
            L3dXUzY3cEp4SXBqT3IvM0xFTVFxMHcKsrdBv31yBHZW/vcHP4C4H5o3Jkl9IB2Z
            7HZIdNLzBJyd9ZwI0/Vl2OuSoEpfNdSM/8Jt9wSQpCYcs4M4lPVcYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T06:27:25Z"
    mac: ENC[AES256_GCM,data:EsaIVvqXDT9eRMomgS4cQdHTifoBcIGYxjEKbDCofJqKCGZkZARPaVBlY3rl8sUtJ46xEbA+8MZJ3Xr7xgKge9keQH8iTEjZGhEA6uNqWkDRXeGpBxVtmekqkWOAhrafPloIt2r+DvQOb/HY+1vzARLp0uoOcKU6d0msm7/rz9M=,iv:fyGP4lC0b4r/HSZlJMLwoWQtQgIUJ3Zt7IQ8GUCyc/k=,tag:Dr2HL8kjsOYG8jI5nY5jdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
