---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 15m
  values:
    controllers:
      *app :
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app :
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.4.9463-630c9f557@sha256:1d7589538a85a48ed3c14703b33ae8bacda7ca7db5307c68e8bc1b8ae6e888de
            env:
              TZ: ${TIMEZONE}
              PORT: &port 443
              PLEX_ADVERTISE_URL: https://plex.${SECRET_DOMAIN}:443,https://plex.${SECRET_DOMAIN}:32400,http://${SVC_PLEX_ADDR}:32400,plex.media.svc.cluster.local:32400
              PLEX_NO_AUTH_NETWORKS: 10.0.0.0/8
              PLEX_PREFERENCE_NAME: "FriendlyName=${ORGANIZATION}"
              PLEX_PREFERENCE_DLNA: "DlnaEnabled=1"
              PLEX_PREFERENCE_GDM: "GdmEnabled=1"
              PLEX_PREFERENCE_GPU: "HardwareAcceleratedCodecs=1"
              PLEX_PREFERENCE_INTERFACE: "PreferredNetworkInterface=eth0"
              PLEX_PREFERENCE_PORT_MAPPING: "ManualPortMappingMode=1"
              PLEX_PREFERENCE_MAPPED_PORT: "ManualPortMappingPort=443"
              PLEX_PREFERENCE_LAN: "LanNetworksBandwidth=10.0.0.0/8"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 5m
                memory: 350Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      *app :
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "{{ title .Release.Namespace }}"
          gethomepage.dev/name: "{{ title .Release.Name}}"
          gethomepage.dev/icon: "{{ .Release.Name}}"
          gethomepage.dev/description: "Media Request Management"
          gethomepage.dev/widget.type: "{{ .Release.Name }}"
          gethomepage.dev/widget.url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values \"service\" .Release.Name \"ports\" \"http\" \"port\" }}"
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_PLEX_TOKEN}}`}}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: *app
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block-internal
        advancedMounts:
          *app :
            *app :
              - path: /app/config
      logs:
        type: emptyDir
        advancedMounts:
          *app :
            *app :
              - path: /app/config/logs
      tmp:
        type: emptyDir
        advancedMounts:
          *app :
            *app :
              - path: /tmp
