apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: media
stringData:
    PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:8vi1jMUo0lWA0QcxIETfcWY4xYRSX+NWdEU=,iv:EWlw6SRtX6s+c5KJPW73VGlyM7tVBaYTbh2LusmgPDk=,tag:C1XUNXDNO94IW+4+obLO5A==,type:str]
    #ENC[AES256_GCM,data:pU5vc8zJmGyPON/cR63IS+RMUUPXxgGfD9h4YVW3jFF7FWZLVF4SHnerpmDEDNAnwBVJ+/IKZjA=,iv:AkXNCSwYWDgTPkSVQ1PFNy9eTcQs3G7BPxfLbK/QIXk=,tag:kpp3DixxPIR5VnjGKZmCTQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NElvR2NxS09lUmhVTjRQ
            S1JrMW9UbXovU1ppQ094S1BreURjTktZZ2hjCkdQd1FKTGZCc0MzOFRsS2tUVXll
            dFNIRXBndjJvVXRackZkL0lZTlhPeE0KLS0tIHFxOFRaL1YwcTZkT3dDVHVzR2Iw
            eWRaS2tIWWhPWE02bitlVXpRTUZ4dzgKis3n357s49jmtHt2e3r2ALwSQn9P/iMa
            qFB1f1e3MNChhp68hYmMVmFhib4UEjbpel3Bwvo4BYmOeBG/ZdPjhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T19:34:47Z"
    mac: ENC[AES256_GCM,data:Z1dfRDBfjTxdgW4QkMl+cccO0gVnL7WryZzDLxSFumLqoMjDfwMmnzD32zIzDvLcIasCngBGyiEthGzenkYmsiquzIvPTIJxHt8MDL4YeyqNGKQzb82HB2FstpHQ7E5caQFcCw6Sub+8c1d7e0Lc/g1i1PitFCW9EeOKAeMLB9c=,iv:U5euGvUwqijeTz4PBtdA4nhn0sIQzhRWQg8rgfyad6A=,tag:YUA8wy0GWV5DSABbuCFWSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
