---
apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-csi-rbd-provisioner
  namespace: ${NAMESPACE}
stringData:
  userID: ${CSI_RBD_PROVISIONER_SECRET_NAME}
  userKey: ${CSI_RBD_PROVISIONER_SECRET}
