apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: auth
data:
  staticPasswords:
    - email: user@example.com
      hash: ${SECRET_KUBEFLOW_PW}
      username: user
      userID: "15841185641784"
