---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
    hajimari.io/icon: smart-toy
  name: kubeflow-ingress
  namespace: networking
spec:
  ingressClassName: nginx
  rules:
    - host: &host ml.${SECRET_DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
