---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-example
  namespace: flux-system
spec:
  interval: 30m
  path: ./example
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  patches:
    - patch: |
        - op: replace
          path: /data/config.yaml
          value: |
            issuer: http://dex.auth.svc.cluster.local:5556/dex
            storage:
              type: kubernetes
              config:
                inCluster: true
            web:
              http: 0.0.0.0:5556
            logger:
              level: "debug"
              format: text
            oauth2:
              skipApprovalScreen: true
            enablePasswordDB: true
            staticPasswords:
            - email: user@example.com
              hash: ${SECRET_KUBEFLOW_PW}
              # https://github.com/dexidp/dex/pull/1601/commits
              # FIXME: Use hashFromEnv instead
              username: user
              userID: "15841185641784"
            staticClients:
            # https://github.com/dexidp/dex/pull/1664
            - idEnv: OIDC_CLIENT_ID
              redirectURIs: ["/authservice/oidc/callback"]
              name: 'Dex Login Application'
              secretEnv: OIDC_CLIENT_SECRET
      target:
        kind: ConfigMap
        name: dex
        namespace: auth
