---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-example
  namespace: flux-system
spec:
  interval: 30m
  path: ./example
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
