---
# CN = elk-elasticsearch-master
# DNS:*.elk-elasticsearch-master-hl.monitoring.svc.cluster.local
# DNS:elk-elasticsearch-master-hl.monitoring.svc.cluster.local
# DNS:elk-elasticsearch-master
# DNS:127.0.0.1
# DNS:localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elk-elasticsearch-master-cert
  namespace: monitoring
spec:
  secretName: elk-elasticsearch-master-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: elk-elasticsearch-master
  dnsNames:
    - "*.elk-elasticsearch-master-hl.monitoring.svc.cluster.local"
    - elk-elasticsearch-master-hl.monitoring.svc.cluster.local
    - elk-elasticsearch-master
    - localhost
  ipAddresses:
    - 127.0.0.1
