---
# CN = elk-elasticsearch-data
# DNS:*.elk-elasticsearch-data-hl.monitoring.svc.cluster.local
# DNS:elk-elasticsearch-data-hl.monitoring.svc.cluster.local
# DNS:elk-elasticsearch-data
# DNS:127.0.0.1
# DNS:localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elk-elasticsearch-data-cert
  namespace: monitoring
spec:
  secretName: elk-elasticsearch-data-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: elk-elasticsearch-data
  dnsNames:
    - "*.elk-elasticsearch-data-hl.monitoring.svc.cluster.local"
    - elk-elasticsearch-data-hl.monitoring.svc.cluster.local
    - elk-elasticsearch-data
    - "127.0.0.1"
    - localhost
