---
# CN = elk-elasticsearch-coordinating
# DNS:elk-elasticsearch
# DNS:elk-elasticsearch.monitoring.svc.cluster.local
# DNS:*.elk-elasticsearch-coordinating-hl.monitoring.svc.cluster.local
# DNS:elk-elasticsearch-coordinating-hl.monitoring.svc.cluster.local
# DNS:elk-elasticsearch-coordinating
# DNS:127.0.0.1
# DNS:localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elk-elasticsearch-coordinating-cert
  namespace: monitoring
spec:
  secretName: elk-elasticsearch-coordinating-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: elk-elasticsearch-coordinating
  dnsNames:
    - elk-elasticsearch
    - elk-elasticsearch.monitoring.svc.cluster.local
    - "*.elk-elasticsearch-coordinating-hl.monitoring.svc.cluster.local"
    - elk-elasticsearch-coordinating-hl.monitoring.svc.cluster.local
    - elk-elasticsearch-coordinating
    - localhost
  ipAddresses:
    - 127.0.0.1
