---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./elasticsearch-coordinating.yaml
  - ./elasticsearch-data.yaml
  - ./elasticsearch-ingest.yaml
  - ./elasticsearch-master.yaml
labels:
  - pairs:
      app.kubernetes.io/name: elk
      app.kubernetes.io/instance: elk
