---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-tensorboards-web-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    - name: kubeflow-oauth2-proxy
  path: ./apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tensorboards-web-app-deployment
      namespace: kubeflow
  interval: 20m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-tensorboard-controller
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    - name: kubeflow-oauth2-proxy
    - name: kubeflow-tensorboards-web-app
  path: ./apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tensorboard-controller-deployment
      namespace: kubeflow
  interval: 20m
  retryInterval: 1m
  timeout: 3m
