---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/monitoring/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana
      namespace: monitoring
  interval: 20m
  retryInterval: 1m
  timeout: 3m
