---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  chart:
    spec:
      chart: mongodb
      version: 14.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: mongodb
  targetNamespace: default
  interval: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: mongodb-values
