apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secrets
    namespace: default
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:Difgu5XKxgZq+HipSyU7,iv:z/dsAUzLMdykKniha9sgyrRK3Ye6Jnf6ZlnlfyDHgv8=,tag:wcJxl9sIbX2Dsh9lZEhOmQ==,type:str]
    mongodb-replica-set-key: ENC[AES256_GCM,data:PM0Vq3SwoVlErPQICMKH0THg/LRTJLBGJgRkboFW4nI=,iv:YWrZwBtz04KOAup1JVWwKh9OGzMM/SilOh4pWPIW7Lw=,tag:/3LpVkROkX3/1nyrzwZS/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcmtKWGt0bm1FblUrMHhh
            YklGRjUzM0NLNmY2WlBIb25ZVHNnUGVwNlRJCjd2K2ZIS1dERGthN3c2cWlDWEJq
            S1lDQzJyV2N4MUMwMUpWeEZnZlNmT00KLS0tIE1hK2Z1Yk4rL0t3OHlvM2gwdjlw
            Ulh6bXpiU1Q0eUlzdENVSGRYM3YvWmsKu+V5huwS5BatrCGejaGHE9Bs1vmxrHRK
            uJ2GpJN19XM7uHJ2+CvAPsWoC9jzLm/WBP+WUJlOuSV+OSZHCeapig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T06:59:43Z"
    mac: ENC[AES256_GCM,data:uBiMWZivc5gWr8No0GV5Z3ZrgsM3QuBi9lBxw7XEd4ALLr55ttGkxGO2HqS1Zj+q/oWh+G1ZU3Se7EqqxOGh6E/TTE4d7CfinW/99ZwdqkFarDrt2I6Hu3BQuhZg5yG7hlmQRU8pTZU+QKaENjyJ+HpSewWTuo0BVgy9bZXd85o=,iv:ZLlSngW9dVIHGWqdL7q9dRo9IJGFoxSrXzUKtcqEyrU=,tag:jaMooEt9J89dH6GCrpXPIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
