---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
spec:
  chart:
    spec:
      chart: mariadb
      version: 18.2.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: mariadb
  targetNamespace: default
  interval: 30m0s
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 15m
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: mariadb-values
