apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secrets
    namespace: default
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:i7EZIFLfx2R0wyvd6Dyq630HTV6Yzhmf4A49kECLxu8=,iv:c7AUwkF+oCiz3K3MbfWMDthLPYNxIB34blM4oGXeme8=,tag:Vs9jugHCSqrxTDyEV77nbQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:Pi9EEDsIIwmnJBv2A7gUBVP6NLo0rgMxqSI14dveib0=,iv:lgo05tkUqT9dHuqHUaaCkWK4CtxZbPzPBcAcOtEjc1Y=,tag:O+lpAoFEfcgoMN+8ioVvHw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:ESVN2DwcjN0PgekiA0HIChHgjHP+ncvdt+JrFR1ygEw=,iv:OEtf8jQJo5QZRFIgYnw+6iUCipfSTS1lt5XQ5Z5yFM4=,tag:zMtmO9VBybTmX+Gp8SdspQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYmZOb2QrWEhTS3BqVm9H
            Q2VCQTFnVlNvbnFtL1JrOXBKbzgvN2tGUUJjCkpaWG9RZDFiZHgvNEtRQnRCbC9W
            aGpGaldtK2dZbElCbFdiRFllTStjZmMKLS0tIFcwSnJHbnN6ME82QzNKMXJBVHpR
            QlpXdjkxNVpJRkU5d08xWXVmS1hPdU0Kkgh7TmmWTmw+G1yh1r2SEhoz4q0/d9hR
            x6HLxx5Sd8Gzj1EBkIF7s54VTgvXtHQFUzxjHJlYGTV/APKoABoy4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T10:16:45Z"
    mac: ENC[AES256_GCM,data:CToipxnpKxH45a5QaXf7gBAdosvRIwa1ME7CjGsGhyoMwrpaz2aEVaeiXWtZvnslo8rtnoE1BryJaxlTiBUgZuXDeRizBNxsFg0AYdzFuSsW1gvgDf2ERb2EhmMGX/oFXSsvE2ib/LMdAtAJ/6JuehYpgDx7SQiKzejGD4lep9c=,iv:Dw84jqaOPE4VMtX1bpfiu6ejzNKOi4QyOYXxGFZ1XeA=,tag:7J9+ajUmFJy7iUtHNCRAVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
