---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/Tuxprogrammer/kubeflow-manifests.git/common/user-namespace/base/?ref=v1.9.1-branch
configMapGenerator:
  - name: default-install-config
    env: params.env
    behavior: merge
replacements:
  - source:
      fieldPath: data.user
      kind: ConfigMap
      name: default-install-config
      version: v1
    targets:
      - fieldPaths:
          - spec.owner.name
        select:
          group: kubeflow.org
          kind: Profile
          name: kubeflow-user-example-com
          version: v1beta1
  - source:
      fieldPath: data.profile-name
      kind: ConfigMap
      name: default-install-config
      version: v1
    targets:
      - fieldPaths:
          - metadata.name
        select:
          group: kubeflow.org
          kind: Profile
          name: kubeflow-user-example-com
          version: v1beta1
