---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./archive.yaml
  - ./ipmi.yaml
  - ./mail.yaml
  - ./media-services-legacy.yaml
  - ./proxmox.yaml
  - ./store.yaml
