---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "media-services-${SECRET_DOMAIN_2/./-}-production-tls"
  namespace: default
spec:
  secretName: "media-services-${SECRET_DOMAIN_2/./-}-production-tls"
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  duration: 17520h
  commonName: media-services
  dnsNames:
    - desktop.${SECRET_DOMAIN_2}
    - lidarr.${SECRET_DOMAIN_2}
    - overseerr.${SECRET_DOMAIN_2}
    - tdarr.${SECRET_DOMAIN_2}
    - ytaudio.${SECRET_DOMAIN_2}
    - ytvideo.${SECRET_DOMAIN_2}
    - localhost
  ipAddresses:
    - 127.0.0.1
    - 10.2.0.16
