---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-services-cert
  namespace: default
spec:
  secretName: media-services-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  duration: 730d
  commonName: media-services
  dnsNames:
    - bazarr.${SECRET_DOMAIN_2}
    - lidarr.${SECRET_DOMAIN_2}
    - overseerr.${SECRET_DOMAIN_2}
    - prowlarr.${SECRET_DOMAIN_2}
    - radarr.${SECRET_DOMAIN_2}
    - radarr-chan.${SECRET_DOMAIN_2}
    - readarr.${SECRET_DOMAIN_2}
    - solverr.${SECRET_DOMAIN_2}
    - sonarr.${SECRET_DOMAIN_2}
    - sonarr-chan.${SECRET_DOMAIN_2}
    - tdarr.${SECRET_DOMAIN_2}
    - ytaudio.${SECRET_DOMAIN_2}
    - ytvideo.${SECRET_DOMAIN_2}
    - localhost
  ipAddresses:
    - 127.0.0.1
    - 10.2.0.16
