---
# CN = store
# DNS:127.0.0.1
# DNS:localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "store-${SECRET_DOMAIN/./-}-production-tls"
  namespace: default
spec:
  secretName: "store-${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  duration: 17520h
  commonName: store
  dnsNames:
    - store.${SECRET_DOMAIN_2}
    - localhost
  ipAddresses:
    - 127.0.0.1
    - 10.1.0.8
