---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: "https://discord.com/app"
              target: _self
        - Gmail:
            - icon: gmail.png
              href: "http://gmail.com"
              target: _self
        - Google Calendar:
            - icon: google-calendar.png
              href: "https://calendar.google.com"
              target: _self
    - Media:
        - YouTube:
            - icon: youtube.png
              href: "https://youtube.com/feed/subscriptions"
              target: _self
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: "https://reddit.com"
              target: _self
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: "https://kubesearch.dev/"
              target: _self
        - homelab:
            - icon: github.png
              href: "https://github.com/tuxprogrammer/homelab"
              target: _self
        - containers:
            - icon: docker.png
              href: "https://hub.docker.com"
              target: _self
        - onedr0p-home-ops:
            - icon: github.png
              href: "https://github.com/onedr0p/home-ops"
              target: _self
        - bjw-s-home-ops:
            - icon: github.png
              href: "https://github.com/bjw-s/home-ops"
              target: _self
        - bjw-s-helm-charts:
            - icon: github.png
              href: "https://github.com/bjw-s/helm-charts"
              target: _self
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
      - OPNSense:
            href: https://gw.${SECRET_DOMAIN_2}
            target: _self
            description: OPNSense
            widget:
              type: opnsense
              url: https://10.0.0.1
              username: {{HOMEPAGE_VAR_OPNSENSE_USERNAME}}
              password: {{HOMEPAGE_VAR_OPNSENSE_PASSWORD}}
              wan: ix0
    - Infrastructure:
      - TrueNAS:
          href: https://archive.${SECRET_DOMAIN_2}
          target: _self
          icon: truenas.png
          description: TrueNAS Scale
          widget:
            type: truenas
            url: https://archive.${SECRET_DOMAIN_2}
            key: {{HOMEPAGE_VAR_TRUENAS_APIKEY}}
            enablePools: true
      - Proxmox:
          href: https://node10.${SECRET_DOMAIN_2}:8006
          target: _self
          icon: https://www.45drives.com/solutions/proxmox/img/proxmox_Logo.png
          description: Virtualized Router
          widget:
            type: proxmox
            url: https://node10.${SECRET_DOMAIN_2}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_USER_KEY}}

  settings.yaml: |
    title: Dashboard
    favicon: https://w7.pngwing.com/pngs/848/762/png-transparent-computer-icons-home-house-home-angle-building-rectangle-thumbnail.png
    useEqualHeights: true
    theme: dark
    background:
      #image: https://steamuserimages-a.akamaihd.net/ugc/2058741574591785827/2336691F8F4832C7E7C2BA1E8240DA78C07A9BCE/
      image: https://i.etsystatic.com/40991675/r/il/b84f71/5798919251/il_fullxfull.5798919251_6ht1.jpg
      opacity: 20
    color: slate
    headerStyle: boxed
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        style: row
        columns: 1
        icon: mdi-network
      Calendar:
        style: column
        icon: mdi-calendar
      Video:
        style: column
        icon: mdi-play-circle
      Books:
        style: row
        columns: 2
        icon: mdi-book
      Infrastructure:
        style: row
        columns: 2
        icon: mdi-server
      Observability:
        style: row
        columns: 2
        icon: mdi-chart-line
      Home:
        style: row
        columns: 3
        icon: mdi-home-analytics
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
      Services:
        style: row
        columns: 5
        icon: mdi-tools
      Media:
        style: row
        columns: 3
        icon: mdi-television-play
  widgets.yaml: |
    - logo:
        icon: https://i.pinimg.com/736x/77/25/3a/77253a53ce061b5eed2e3924739ab89b.jpg
    - search:
        provider: [google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Hey Spencer, how are you doing today?"
    - kubernetes:
        cluster:
            cpu: true
            memory: true
            show: true
            showLabel: true
        nodes:
            cpu: true
            memory: true
            show: false
            showLabel: true
    - openmeteo:
        label: Madison
        latitude: {{HOMEPAGE_VAR_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_LONGITUDE}}
        timezone: {{HOMEPAGE_VAR_TIMEZONE}}
        units: imperial
        cache: 5
        format:
            maximumFractionDigits: 1
