---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: homepage-config
    files:
      - config/bookmarks.yaml
      - config/docker.yaml
      - config/services.yaml
      - config/kubernetes.yaml
      - config/settings.yaml
      - config/widgets.yaml
generatorOptions:
  disableNameSuffixHash: true
