apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: default
stringData:
    HOMEPAGE_VAR_TIMEZONE: ENC[AES256_GCM,data:0n2eH+Gt3mvgIEYmG09U,iv:7v14Lw/so9jEd/yyLM0OPDU7mqMyGEk2FhInHz+b3io=,tag:kUs8YN6jXOyZHHjFiP8Lfw==,type:str]
    HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:mUu26HSHr+7g3w==,iv:t2Jpt+T0J+E3iZWIj2xaPIJLub44nhOaMmfnuqprNPw=,tag:oxmhCFbZm9DMSLphr8S02A==,type:str]
    HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:QCFFBXYwhbIePTs=,iv:0tjF93d6hC7Lp0/HVvP2onYXtvJT1SXaYv7W5OZal80=,tag:0qDDnfLv2mN/KeHsfgRZCg==,type:str]
    #ENC[AES256_GCM,data:HMJmdZ95Mwo=,iv:PZ+/b8zdWZ4g9bhvORjZk2i2YAgi71K5NxebUF5wFsk=,tag:I4t9MbZaVPlgb3TGxJ8lRA==,type:comment]
    HOMEPAGE_VAR_OPNSENSE_USERNAME: ENC[AES256_GCM,data:7pDnM+Qg4HZoTjXb3r2qKrn/f5B1KRwTqYzAiolNGnoPUp+yN/lVqWsVtdE7AcZrI8n+iO+vpOQiKebybQHJC6hPW0RenQzVLPPZVUrfu/U=,iv:QAtKD1viuc5EZwLrpwylfeUpxV5MrV/xW/sj07N3oTE=,tag:zUGW8Ya74dV7tfGLOfCbHQ==,type:str]
    HOMEPAGE_VAR_OPNSENSE_PASSWORD: ENC[AES256_GCM,data:a9VcOQpRDI1lgwaMkeGuH8xSVOiFh11MGPmuri3Y8d6+J3XGNOn6Ij624lvTCPCtQwK6Y00rxDeUM6o5CmnXkdhuZMbktozTOdfq7AjjOd8=,iv:ztiBtks9vE5HLrc+3f24IiQsWSC8pnmgFMcatikAp+M=,tag:jM2xGerNZM/HJb1z3a5y0w==,type:str]
    #ENC[AES256_GCM,data:BpV1ZjjPs3ZO+19iA+wK,iv:DFewLS4t0Ij36EO+999Z4+KoRVj7obNxH7lQfT6q0cA=,tag:tUa2+uiLmXVC1lHa7Ht/DA==,type:comment]
    HOMEPAGE_VAR_TRUENAS_APIKEY: ENC[AES256_GCM,data:4xp/OlfGPbvhgI5/JkKecs21t+UjDDAFAKfe7cEQXpPd5+9Ki6alldn6zWR3wUlBclbdrUOZDnaIK/19iUYNmI4D,iv:OZJa0eIg07h3zQCZKQqSwYheaTeY/wd3qSrsfn6X2HI=,tag:+lznA5oG+dbpYD539OpPEA==,type:str]
    HOMEPAGE_VAR_PROXMOX_API_USER: ENC[AES256_GCM,data:OUUajRJYxZanPpTClkd9nQ==,iv:+o1wEdDg1buvXpDqNY87I3nPpmyzQc99CJC4C4neLmw=,tag:wRT9bE0/bY5UYcEPduo2uA==,type:str]
    HOMEPAGE_VAR_PROXMOX_API_KEY: ENC[AES256_GCM,data:NOsDUCLJIsTzn6jpiLP3YHv0MnZmsQ5xMgge/6BMr/fhmZ7V,iv:V3sNf6RNJxwh34ggB+lJVEkwvDJ/Fz1SdqWN6Vt2WIs=,tag:0GAZLtM66RHjK5BuSoebdg==,type:str]
    HOMEPAGE_VAR_PROXMOXBACKUP_API_USER: ENC[AES256_GCM,data:V61DcAr7QV70/tp4KS1pfOL2IWhiXzmU,iv:L4xS+i6rEi8FpM52pjklQi1+PY/YMTwSh36LR9i+sK4=,tag:YgQdZ+tXawoNItztNwn74Q==,type:str]
    HOMEPAGE_VAR_PROXMOXBACKUP_API_KEY: ENC[AES256_GCM,data:bdCKL7a6r5aYTst2rRv8AODMKSjqwRYssKpnOosDHKK3QqCv,iv:pPiUy8XmlibxK6sfrjVBB7k9y7CnjxfH1Wuz6AIRtJ8=,tag:AU/zLVxlETspMkyagJjiHA==,type:str]
    #ENC[AES256_GCM,data:CNNrJE0h4Go=,iv:kxLHDx2ZW+ndNn/6Zs2r4eiwy53jgWaAdY3Tb0HAiSQ=,tag:pPpGJgNXKAcf84vrZcGngQ==,type:comment]
    HOMEPAGE_VAR_OVERSEERR_API_KEY: ENC[AES256_GCM,data:0FChqOEBsieEkq1akjyjK5gi7BljXfoCgtX8M1mFyXqvd7IReJE6UBKzU522OUijurO4Tp/hQ6MVvg/oOVSC5Jsz75M=,iv:tI11ArF5jD36BzoH6/xl/2+IrK+E15kvrCl0KmiaddI=,tag:wUJelg4YC7xAAKfz03NwSA==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:tliLQ8hT5QC9DcIyeCYsTqxKrW8=,iv:g7zGhih/EmwMcL0Z6FGqyUBEghpUQX7CkTZT60G1iQA=,tag:6U0xh+zxmrmG9RbWP0tQHw==,type:str]
    #ENC[AES256_GCM,data:psn0h0CQW9DA/YU=,iv:KyuEVXNIn9xRM/JBV5SWewMjJaTgpk8hFKxzsjy80vA=,tag:5KLOC4TUeqqxD4Lg/OmKEg==,type:comment]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:IKM3RTI=,iv:uGAAIldpiSZ4slcL1XlEzU/jTniemHJmQt7sd9JD8pU=,tag:TB+/N92XLrUTPRCO51LBdQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:N9Ji9LaiNqJDcjr7IQaV,iv:ZRyJqDg8eLLZMsFAwe4mOkgCu6X1M1vWXHqEEPTo5qY=,tag:u+JqCQ7Ou2UrIMcnf4Mu3Q==,type:str]
    #ENC[AES256_GCM,data:uFTLnY/7k1b1O2Y=,iv:Ljiqce9Cp7GFPM+TuBQvromnfBNEg3EVUfMIUwX2rKM=,tag:bItliYrAvMYLwUpEpALXNw==,type:comment]
    HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:PYZ+7Dvnbu4d+d55hDUZ5ETR4DBAiZ5gLGpcMarxAgPTwFNImFoiwiEIB2uug+lfOu0=,iv:rCurQG1z3VthebtmRqKySFqF1izS0gXAy0SKQrA+4IU=,tag:qz2wUrM+rPO5WMJzemCnkw==,type:str]
    HOMEPAGE_VAR_WORK_DOMAIN: ENC[AES256_GCM,data:8cbzBviyYEh4zg==,iv:UHaGG6Pwk3i9ga8+Q/8/QjeE198v4w5WIgq6PqXn+zk=,tag:1w3zmmaBJIpyoy3ksxxcxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeEt0OTJLSkF6eW9ydlNq
            ZkVjTVFvZjAxRVlnMk4rdEVySmJPbW1iU2djCllDV3NFZlQreG4xRU5YSnMwaThs
            VHJJUmE0cXBMMlFYUEREYzJFUG5nQXMKLS0tIEEyZDkvVHZTM242VmdYdjR6b2kx
            U3d4bXY5YkJHUXJyZFkrWVdJam1GSzgKgzNh3YosQrNCQ2Mfi7hJIRU0VIrfSs/V
            uZe9rRNYIiKHzt9daNbjwJaZ13pzZI3iU77J7Atnuy+dZz838PQXrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T17:22:22Z"
    mac: ENC[AES256_GCM,data:YbmQWygDxWim67GXUGx7qI3I2zB8AE/yzgcHR4boHQ4giCLg1kCsh0zAWLP5ANb5Y8pD8qC+71PM/0krtqMuNrPEkx9gvN5Q54t9lXxTeo9kcqpltdWDxKJSB/gg/DrSXKaRn8j6tzSkgR6uEl7bcWf8NAJ9P0pML1mcOWxXt/k=,iv:RuQfw+XUd+kH/ZKcrWB2iGZ8QiT8AaRNiNtfdSZj0gA=,tag:liYYU0uDV3plI58wnjc39g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
