---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml
  - ./server-plan.yaml
  - ./agent-plan.yaml
