apiVersion: v1
kind: Secret
metadata:
    name: external-dns-2-secret
    namespace: networking
stringData:
    rfc2136_host: ENC[AES256_GCM,data:KbvTyXY/MzYdGFJGjwps3g==,iv:4MTPUws2u7lOAzRfeb5WqUONKB6+gF9t75Yn+k7J5II=,tag:jOyP8EnxmeJoWosgutf3rA==,type:str]
    rfc2136_tsigKeyname: ENC[AES256_GCM,data:oXcc1TbxO+4T,iv:kQlTGfivJ2G6MyggQVclB6q6f2JA/FGA84QOXtZ6Zwc=,tag:7kxZ/vp9SC4tN/Btot8TTg==,type:str]
    rfc2136_tsigSecret: ENC[AES256_GCM,data:kK57PwIvSWNrU/SbOoXSdPBBPavQEUmUyHgdQn0CNTQhatYJD7XunSiTiTVRbhPKT5RnuuRSy7l2JcvQjb/P2McjESXqAp9ZqhPmUdJWXPhf2JFxKxf1OQ==,iv:weZJC3Zn3FB1uDsYXCjsm+aUInUol7hVzdoMI6D4WDI=,tag:uU/C0pR80PQGTzuZ84atTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMXpaNXNURXpvcmxyQjNT
            Z2h5WTdUVHEzWTVCNmRtS1pjTmRqMXVJQ0F3CjNxSEVNUDJOOGh3NXFLTW1WWkxU
            em1KdEZXRExpeTFVL1BXMGVzZDJXNk0KLS0tIGFib2Jhd3lBY3hoQjducDNNRVNE
            ODNQYjJYZTRwZndxOURYQXRlVlJXVFUKP/SF9rc+FGfxIPzY8kgTU5tKybG6l/jA
            0XZIZrT3SVia4YSYeITOleMXcsyhwXDV3Twmx/SNR/NQavl9P3ThYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-14T04:42:36Z"
    mac: ENC[AES256_GCM,data:mn4Sz+7vlAuzUvCJMwPjnEW31O/qdvJ2RtHAvwn1psbjuB5XI+2s6HHxhsv7BE7ET9K0Boe06q89cfGcA9eMfYxvHBW32KJd9oyV60LjhOLOcBTPRT28o9OuvukF3fvuzoDmVLiMJw5P/2JNGQYlVrvCAJWZ6J90EmQ1W6/X6mw=,iv:kCYONakip6cTltEmeEj2L6KW1Au4wOzZuGKlgNRbFPk=,tag:1Rasg7GoG1w0FQplU9Dmkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
