---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: gtnh-discordintegration-json
    files:
      - config/discordintegration.json
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: gtnh
      app.kubernetes.io/instance: gtnh
