---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster-external
  namespace: rook-ceph-external
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.11.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 60m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 60m
  uninstall:
    keepHistory: false
    timeout: 5m
  values:
    # optionally, the ceph-mgr IP address can be passed to gather metric from the prometheus exporter
    monitoring:
      enabled: true
      rulesNamespaceOverride: rook-ceph
      externalMgrEndpoints:
        - ip: 10.1.2.11
          externalMgrPrometheusPort: 9283
    toolbox:
      enabled: true
    pspEnable: false
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      external:
        enable: true
      cephVersion:
        image: quay.io/ceph/ceph:v17.2.5
      crashCollector:
        disable: true
      dataDirHostPath: /var/lib/rook-external
      skipUpgradeChecks: true
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s
    cephBlockPools:
      - name: ceph-k8s
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block-ext
          isDefault: false
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph-external
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph-external
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph-external
            csi.storage.k8s.io/fstype: ext4
    # CURRENTLY BROKEN DUE TO VERSION DIFFERENCE BUG
    # rook-ceph-operator logs
    # ceph-file-controller: failed to reconcile refusing to run new crd: local cluster ceph version
    # is higher "17.2.5-0 quincy" than the external cluster "17.2.5-0 quincy", this must never happen
    # cephFileSystems:
    #   - name: ceph-filesystem-ext
    #     storageClass:
    #       enabled: true
    #       isDefault: false
    #       name: ceph-filesystem-ext
    #       pool: ceph-k8s
    #       reclaimPolicy: Delete
    #       allowVolumeExpansion: true
    #       parameters:
    #         csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
    #         csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
    #         csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
    #         csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/fstype: ext4
    cephObjectStores:
      - name: ceph-objectstore-ext
        storageClass:
          enabled: true
          name: ceph-bucket-ext
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
