---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-external
resources:
  - configs/common-external.yaml
  - configs/cluster-external.yaml
  - secrets/rook-ceph-mon.sops.yaml
  - configs/rook-ceph-mon-endpoints.yaml
  - secrets/rook-csi-rbd-node.sops.yaml
  - secrets/rook-csi-rbd-provisioner.sops.yaml
  - secrets/rook-csi-cephfs-node.sops.yaml
  - secrets/rook-csi-cephfs-provisioner.sops.yaml
  - secrets/rgw-admin-ops-user.sops.yaml
  - configs/ceph-rbd-ext.yaml
  - configs/cephfs-ext.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: rook-ceph-cluster-external
      app.kubernetes.io/instance: rook-ceph-cluster-external
      app.kubernetes.io/part-of: rook-ceph-external
