---
logger:
  default: info
  # logs:
  #   frigate.record: debug

auth:
  enabled: false

tls:
  enabled: false

mqtt:
  host: mosquitto.default.svc.cluster.local
  topic_prefix: frigate
  # user: "{FRIGATE_MQTT_USERNAME}"
  # password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  global_args: [-hide_banner, -loglevel, info]
  hwaccel_args: preset-vaapi

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 0
  alerts:
    retain:
      days: 30
      mode: motion

objects:
  track: [person]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
  streams:
    cam-1: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=1&subtype=0
    cam-1-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=1&subtype=1
    cam-gazebo: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=2&subtype=0
    cam-gazebo-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=2&subtype=1
    cam-3: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=3&subtype=0
    cam-3-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=3&subtype=1
    cam-garbage-can: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=4&subtype=0
    cam-garbage-can-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=4&subtype=1
    cam-front-door: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=5&subtype=0
    cam-front-door-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=5&subtype=1
    cam-back-gate: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=6&subtype=0
    cam-back-gate-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=6&subtype=1
    cam-driveway: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=7&subtype=0
    cam-driveway-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=7&subtype=1
    cam-back-door: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=8&subtype=0
    cam-back-door-sub: ffmpeg:rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=8&subtype=1

cameras:
  cam-1:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-gazebo:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=2&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=2&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-3:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=3&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=3&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-garbage-can:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=4&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=4&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-front-door:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=5&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=5&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-back-gate:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=6&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=6&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-driveway:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=7&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=7&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
  cam-back-door:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=8&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://{FRIGATE_LOREX_USERNAME}:{FRIGATE_LOREX_PASSWORD}@{FRIGATE_LOREX_HOSTNAME}:554/cam/realmonitor?channel=8&subtype=1
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
