---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: generic-device-plugin-configmap
    files:
      - ./config.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: generic-device-plugin
      app.kubernetes.io/instance: generic-device-plugin
