---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
    - name: kubeflow-oauth2-proxy
  path: ./kubernetes/apps/kubeflow/ingress/kubeflow
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: kubeflow-ingress
      namespace: istio-system
  interval: 20m
  retryInterval: 1m
  timeout: 3m
