---
name: "Meta Labeler"

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4.2.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
