---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-homepage
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-ingress-nginx-certificates
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/apps/default/homepage/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: homepage-sub-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: homepage
      namespace: default
  interval: 20m
  retryInterval: 1m
  timeout: 3m
