---
# Configuration specific to Sonarr
sonarr:
  sonarr-chan-${SECRET_DOMAIN/./-}:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr-chan.media.svc.cluster.local:8989
    api_key: ${SONARR_CHAN_TOKEN}

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: anime

    custom_formats:
      # Globals
      - trash_ids:
          - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers) (1400 )
          - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers) (1300 )
          - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers) (1200 )
          - 30feba9da3030c5ed1e0f7d610bcadc4 # Anime BD Tier 04 (SeaDex Muxers) (1100 )
          - 545a76b14ddc349b8b185a6344e28b04 # Anime BD Tier 05 (Remuxes) (1000 )
          - 25d2afecab632b1582eaf03b63055f72 # Anime BD Tier 06 (FanSubs) (900 )
          - 0329044e3d9137b08502a9f84a7e58db # Anime BD Tier 07 (P2P/Scene) (800 )
          - c81bbfb47fed3d5a3ad027d077f889de # Anime BD Tier 08 (Mini Encodes) (700 )
          - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01 (Muxers) (600 )
          - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02 (Top FanSubs) (500 )
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01 (450 )
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02 (400 )
          - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03 (Official Subs) (400 )
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03 (350 )
          - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04 (Official Subs) (300 )
          - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 05 (FanSubs) (200 )
          - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 06 (FanSubs) (100 )
          - b4a1b3d705159cdca36d71e57ca86871 # Anime Raws (-10000 )
          - e3515e519f3b1360cbfc17651944354c # Anime LQ Groups (-10000 )
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1 (-10000 )
          - d2d7b8a9d39413da5f44054080e028a3 # v0 (-51 )
          - 273bd326df95955e1b6c26527d1df89b # v1 (1 )
          - 228b8ee9aa0a609463efca874524a6b8 # v2 (2 )
          - 0e5833d3af2cc5fa96a0c29cd4477feb # v3 (3 )
          - 4fc15eeb8f2f9a749f918217d4234ad8 # v4 (4 )
          - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV (3 )
          # HDR Content
          - b2550eb333d27b75833e25b8c2557b38 # 10bit (0 )
          # Unwanted
          # French subtitles
          - 07a32f77690263bb9fda1842db7e273f # VOSTFR (-10000 )
        quality_profiles:
          - name: Spencer Home
          - name: "!Spencer and Friends Setups"

      - trash_ids:
          - 7ba05c6e0e14e793538174c679126996 # Multi Audio (French) (0)
        quality_profiles:
          - name: Spencer Home
            score: -10000
          - name: "!Spencer and Friends Setups"
            score: -10000

      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio (0)
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored (0 )
        quality_profiles:
          - name: "Spencer Home"
            score: 101
          - name: "!Spencer and Friends Setups"
            score: 101

      - trash_ids:
          - 9c14d194486c4014d422adc64092d794 # Dubs Only (-10000 )
        quality_profiles:
          - name: "Spencer Home"
            score: 2000
          - name: "!Spencer and Friends Setups"
            score: 2000
