---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-katib
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-rook-ceph-cluster
    - name: kubeflow-oauth2-proxy
  path: ./apps/katib/upstream/installs/katib-with-kubeflow
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: katib-controller
      namespace: kubeflow
    - apiVersion: apps/v1
      kind: Deployment
      name: katib-db-manager
      namespace: kubeflow
    - apiVersion: apps/v1
      kind: Deployment
      name: katib-mysql
      namespace: kubeflow
    - apiVersion: apps/v1
      kind: Deployment
      name: katib-ui
      namespace: kubeflow
  interval: 20m
  retryInterval: 1m
  timeout: 3m
