apiVersion: v1
data:
    accessKey: ENC[AES256_GCM,data:15Nb6CGWtXRxwsT9EjtvpF5uzW2zusZuvgqtvw==,iv:yJynLUySb2rnVOtzxk7VsJgbT7uOiSAE5KHoXjnlupc=,tag:GNIyj2F0Fpy/floAv+aSCQ==,type:str]
    secretKey: ENC[AES256_GCM,data:hKG3MasIEXna2LTPEC6dbS/erUiiPeXaACtZcDqjIkekjp7CWVN+ITzj8GLvBwKZKp9w+EXPKj0=,iv:PqtSLqtgXEnJpBrnPe5nVyV55Sn8WIUIgJSGiCacVc8=,tag:rPIPJQrI0WnD9m+klCFhWA==,type:str]
kind: Secret
metadata:
    name: rgw-admin-ops-user
    namespace: rook-ceph-external
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQTlaVldOcHZRS0cvSlNy
            T2o1RFh5dlhCR1hWeEpHTnkwajZ6U1RPRFZnClFpQnVsZUF1K0xaUVZ4TXN0ZkMy
            NDcrRm9xVFNkT0pnQjIyT1owSS9UclUKLS0tIE1HVkxzNnZzekpEdjB1UGRWQ1Jw
            N2xHOU5IRWowZUZDbGhKaW4wYlZ3cUkK8cbamKo761Fye3KJdYq9qle5mAj+mX/9
            dSheQhRlyit2JzgTOR2zYEmm1l7CZQFYyFI1vw+ado2Y9kEOXFzkug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:39:48Z"
    mac: ENC[AES256_GCM,data:GvM4cnB7EouE91C7nUYW5s483ftf+GX/m0xW6K2d4f52lEXJ6S4o7hmjAeH44A3mGWkmaH68Im8MVfZd5K3OFZanjX2LGCq0GxS082k/9cMc2DhGj7KzrsssmrTUJ61nL7TNOnlFCgiamdaO8+zr5Uv18dvi913bnkmEJz3HbcY=,iv:R6xFDPylGIZt0VAqBy03RwsUnClDwgHrj5glg7XyZSM=,tag:rFNEiV2HZDfpHKybCl3quA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
