apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:MsdwQlVHfS3Glqr5J3X08nYkQBiWqAF2REZCMQ==,iv:396UI6sUV5gPx49RG/HCYD108fYiFBx6eClj2E7OrEw=,tag:rw0Js3VfcAKdgE3h3CmoKA==,type:str]
    userKey: ENC[AES256_GCM,data:WcilBw6DZxmohtcr9Uo5gfJ98HtO6X8r21TtYHovxH+O8cpchs5eURo3Ufmn8DrTX+QAFiIKYWM=,iv:1P2J0tJw2v//twuPx5lIdyH3aJtpa1K9lO59G1m8VyY=,tag:PFh9FrNqtmrYUj9172PVLg==,type:str]
kind: Secret
metadata:
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph-external
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY0JyTEZOVGU5dGpMR0Qx
            dG1SWkpyTVZnc2ljOS9Ic1plditQdmNpY0NZCjRad1p6bXdIcDJxTUw1cGUvbE5G
            WWFvTzEzOG55YWtWNStzZjhnNWFrZ1UKLS0tIGh4QjhiTnRtWHhiWTNpSTdVeHJR
            SXhtVngwcnRGMzhPdHErL01FV1kyN2MK14knsamgV4Y3pSDzmMXz0FgDTScaMHT+
            gAogM1JdU0rWvhNTQyW4XSf1qO6c+1ADWhoJqhoBReDv55v072cxiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:40:29Z"
    mac: ENC[AES256_GCM,data:6fnmusS2KYylWSsIoBpo/5TUowHPqTnfwCfWzT7FRphwoeaKLSurl320iH6/HfcPFIUlILxbb77DHmZdBx26b10PF0zEujBcrQoAedlE8s/0RyFgAXMOBjG+/2vqW7PygOpD1lLCAuewxg95e6NwjTHGsQ9+hp3rQAPbtlGH4XU=,iv:w7AiZjXYI/4b3Uo2GDl/b/UBIHIncXz3lV/S7SAcfD0=,tag:Fy7RvBn5woegPvIhoHIG/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
