apiVersion: v1
data:
    admin-secret: ENC[AES256_GCM,data:hWmoZwchHQfF7KH0rM4vJA==,iv:wawLpbDg8k+weO5r/H83Tj6TsW4ydyuLMFSZ8QfdeUo=,tag:6bqx8IhUArs9QyBZdgZtRQ==,type:str]
    ceph-secret: ENC[AES256_GCM,data:3+HlcyGRfIAmVpQHzpyRs1VeUiTXOKpRQ/laAb3Om2ryfgdoDDMOs9RxsZemBu70RXSREF8SC/w=,iv:nckyEeZrXsdN1THgDUfyoAE23AtrSOZL1NnN8rFhEl4=,tag:+s+kc9I3zBJOUKYQ1V8Gcw==,type:str]
    ceph-username: ENC[AES256_GCM,data:6sVATB/1pRsuydVM0FTzvp/aMB8UwH7W5jYv/A==,iv:o70vrW/o8v7G9ELxHwAT0QZD43IO3tL7VDVV/1OOaP0=,tag:f6qaS9pNkJKbJH+D9lTL8w==,type:str]
    cluster-name: ENC[AES256_GCM,data:8E/44cN6RYcOib5QkHYUbDrYxz+PL0nn,iv:IrlU38tWGqx40TQvlEICHsuncX7SG6ou9AfSQVTcxGA=,tag:YvQ7jiXN9olzbkUCkBeO6w==,type:str]
    fsid: ENC[AES256_GCM,data:Acwlfjn/hFff9NEz4oFZB/auwAxJzCxRZkV+ThASrRStG0Ta9ez2IxwOlQP+Efml,iv:PuKL6sp2yiogk2A6DMmwcg1tJiSo49M9bODoAY8cNj0=,tag:+MGf/JrsoPN43tosJXhU+Q==,type:str]
    mon-secret: ENC[AES256_GCM,data:UID54XqTUOHnNtTKXq8gVQ==,iv:qyj8pJrPDty70OahkMZjcNWQSsm4auc9e5FoE9bwx7Y=,tag:OjxkHzj+4w3LNdJofADBaQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2023-03-01T06:05:02Z"
    name: rook-ceph-mon
    namespace: rook-ceph-external
    resourceVersion: "5334865"
    uid: 39d5a139-e330-4330-b4da-bb7fa69e8c73
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTWJGMnEzZkNndnNvYXl0
            NTVGSDNYSW85WFNGS05yWVN4VG5FU1hRWUNFCjZkZS94RmdlVzFOdkF1aEpFdyt5
            eU01bjFsT2lJb3RpRkV5ZlpYT0RqQ0UKLS0tIG1GbHI3SjlvMVM5UklJZVBRUTkr
            SFArNWFxbjJaekVzZkJEdGVvQk9keTAKwVSZwYu8cL/2V+Dap3HujHCdfim/jd2R
            UJbTsETgBkt4+sIG+tIzdF6Vl8j7vQVhK3yyTB6aNJrE4GEXuL8OwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:13:33Z"
    mac: ENC[AES256_GCM,data:qYC/JM75BOi+IBjWowTigKFzSS4CZjhyJsUrgHHFBZbM44OaZb/Ffqz4Tx9vPt6PHfeHRLgvz0W07Kv8jacEvv2+hsMn2/HZim3yEN7/In90psgXuq8PJDMlXwH7axIExJDH0kw0nVfCNOs+zwW6VMr7zfYo7FJ7mPV8gMmmGxI=,iv:iICpBwJU9sauqj5eIun2V0oVW37Ozrf9Kqtuqz9+mUo=,tag:rGXdCF9rtJXj/HLrf4yl7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
