---
apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph-external
data:
  adminID: ${CSI_CEPHFS_PROVISIONER_SECRET_NAME}
  adminKey: ${CSI_CEPHFS_PROVISIONER_SECRET}
