apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:bEp2SYJOqtn/CPeL+U+wQecITGtfaBTTpggMD+SfJ3A=,iv:nK9mEwjb9Bvqu/2B9G9siVrz3aSfZ9oF8UwMgkwcxyI=,tag:D0jmR9eCOHvb1Rxst4NK/A==,type:str]
    adminKey: ENC[AES256_GCM,data:idvCm75PdMHjApRz//N5hrSm9upai3lpLYCmeoDbF9heQnlCVwWC69yWpIYx8SaYD/cB48P+7AI=,iv:j1rTnHh0m5Kvz71lvK86pnacSn7p+mFHNa7u89doPS8=,tag:8S59mA5NmdiuoeE/R+nF/g==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2023-03-01T06:05:04Z"
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph-external
    resourceVersion: "5334887"
    uid: 90daa0b6-3dcd-4ba7-8f1e-5d6b9f063e09
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VW9lckFTOGxEMUJJU1Zr
            d0xpS1ZLbXh4NW1vNHdQYzdpTnZ6aHFFa0VVCkJtVkx0YVY4dEdrYk9IeHpJV3VC
            eXRMcVdNcW9ONDd3VWQ5TVJDOVBGTVkKLS0tIDNKdndERUR0VDVYalZoc1ZpbVd3
            Q1BVNEsveHJpdFBVY3NpY3BPbGNhNnMKdofXCqOwAQeGPIlxCRPdVnXsAfVleoBa
            UssQkpglKTMOub41XnMilpLSYaIkyuDGCZ1cgGwYzmxKfyqKwm7BWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:14:24Z"
    mac: ENC[AES256_GCM,data:ETFEL+poNW/5+sEB7l43Q1tD+141Y05DMg+BCWESQ9lqSU5XxEbyrsGi+VNE4teETF9UbAI9IAe59LMyWYhG+sjoJnieUB/E6CcS4nyDSIbiub0fGM1sY8F/T0H/ZdWojMkyaosob7jHkpLfaCG/oguYAHTJVQz3cBD5mSiU73Y=,iv:w8AtXKNVstC7Wruc+dHNm5fl/7+1SIorcQwbD3qq03k=,tag:FkfHX+QlzJHFjP8TLR0xKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
