apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:raj5LDG8hil9xyBLjETpSQ==,iv:aQQxyrYKexninM8aOoqSxvVE10Psb8nZasoJrSgRetY=,tag:yGa+hAnja5S/P5BjlljIiA==,type:str]
    adminKey: ENC[AES256_GCM,data:+WOCkL2vVDHxtGG0WnML1Tl55YRyylkgpkgwhbqimVPrvBBwMgcxuhnPd2Mpr7rFuNKcQb9cE7E=,iv:VrgIKfhxMac1ukVODMkpxRN/ANM2sZKO1JWdlwVt3Iw=,tag:t7LlsSBCIrFFHBE0TistGg==,type:str]
kind: Secret
metadata:
    name: rook-csi-cephfs-node
    namespace: rook-ceph-external
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z2JIdmF1a3FVT2lNWWZs
            NlhyWk4vSVBwdm51VklKemIyNm1TODJrRnpBCkVLYkc3UGhTeG9TQ291U1FDeVFQ
            OW0rWElCbythazAyZzdoQVZIeVA2UTgKLS0tIDhmMkRCaUVBeEtrc3g4a3pnVTVt
            MDg5QmpmaFo5aTdUWjBlcWJiVDhKOGsKxfxO57jjVHXxjF6xooQJ4gZ33vLO06aX
            W1ejvzCnUAzmgFwfOza2kR0kVPSfYhGZwDpNOggMvApwjwfqH/qXAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-22T02:42:13Z"
    mac: ENC[AES256_GCM,data:nQo16e5GkZBnKRmSCEaan2qhzqsGcp/bqxfi5ujz1IZhsHtL9LSMWiP+yBs8zrrZW1g6CQDaAFbiZ2i7olOLyKGmoarJ6TTrHsho5V24QPHa1yH64/ahvpyusqTsSf1XPpukgitfsuzVniv1UGP4eu0v9/m0W0Ei0tqz4TlIfE8=,iv:TZsgIYwJVa9CKKXXPUdfP+vGfj3mxkrqfDAs06egU2U=,tag:XDRlFqnJgsiiVpcAM/kPTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
