apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:Psi94hmyliikZ0Gy1fg4JQ==,iv:2FyqWNlrI3EUkiQ72QlLS/0UJpdjYE4NHb1SWHdVcFI=,tag:qCtjCV2Ed9Qo1kcaLkGyTA==,type:str]
    userKey: ENC[AES256_GCM,data:PPTi3GdmWvEXY2in6vkgwDpeDNLxXWemH513TFWocKrn8oVxlORCY5vhOLlHVLy+TtX1KZ6p7Y0=,iv:WikqAiYU8p7Do3CF9Jy8sVB6/7iSLjHUq6pvR7yj3bU=,tag:vdTnlv8FO0jjrvhbpRBXjg==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2023-03-01T06:05:03Z"
    name: rook-csi-rbd-node
    namespace: rook-ceph-external
    resourceVersion: "5334876"
    uid: 0b1de7ae-e8f5-496c-94d5-26c99ebb7599
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb202cDAxUUVpa0EyOXQx
            cWpaemJhVUc3VlRtY2ZqRjNndEdwOUh5RFJZClB3NzY0Mlo0akxUb3V6YXg1ZG4z
            YldadHVvSVBGcStVeDNtYVV6U2UvMU0KLS0tIGkwZVg0bzJYMWkxczJGREFkODFs
            TG5TQW1waDYvMGMxZk9TMlRoYVhtdzgK0HjLRm5ebEobzfiIDcW7bymr5ijlRK7k
            O/avZdLb7rWgRBUtzrlvEMVfXqagVaxbSr+t/hN4/PV2WhGlILNe1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:14:31Z"
    mac: ENC[AES256_GCM,data:xsbJx/7nT/vrrf8sowg/nNG4IHM7mHgFaQABSQlyAzcokkedfYHCI3ymATyHselxILJkBrOC+pLHe7k1Wmz/ZrNMSqD61x1T+O6Wic+pKYALG6r2/6sQDcSPZ+fvm9LiIeLZ0kowX5wJ5M8ThV4JJwjxi1yFFj9Wnu+/ioCXajk=,iv:yeIs1Vnx4yUu5WxiOttkMaSJYy0IStgswg5HP5cUK2M=,tag:N/xROLjOL0T/m62+/mPLOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
