---
apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph-external
stringData:
  adminID: ${CSI_CEPHFS_NODE_SECRET_NAME}
  adminKey: ${CSI_CEPHFS_NODE_SECRET}
