apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:eBGhulzjiA98i1OVXOiCXg==,iv:WrDKjTPWvOU/XqDiPRtmy5EdlXZczamWjtyyX8p1FdI=,tag:+WqizlwBjUxKHNTfiiRYXw==,type:str]
    userKey: ENC[AES256_GCM,data:WUkNnbsNB/9/nzaiF5rBSzrUFhydg3/WO6b217OAwujH8zgL+9uSbg1h3DzZUoo9e5ZW0YKKrFo=,iv:Q69RvDktd8MwB4aLoJ8e3rtJkEqxOMb59M8cWtAoKic=,tag:TK0tstjwmUkutnuB1KmFZg==,type:str]
kind: Secret
metadata:
    name: rook-csi-rbd-node
    namespace: rook-ceph-external
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb202cDAxUUVpa0EyOXQx
            cWpaemJhVUc3VlRtY2ZqRjNndEdwOUh5RFJZClB3NzY0Mlo0akxUb3V6YXg1ZG4z
            YldadHVvSVBGcStVeDNtYVV6U2UvMU0KLS0tIGkwZVg0bzJYMWkxczJGREFkODFs
            TG5TQW1waDYvMGMxZk9TMlRoYVhtdzgK0HjLRm5ebEobzfiIDcW7bymr5ijlRK7k
            O/avZdLb7rWgRBUtzrlvEMVfXqagVaxbSr+t/hN4/PV2WhGlILNe1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-22T02:42:40Z"
    mac: ENC[AES256_GCM,data:ejlfBJHphpAvtBx7p9R0fBLXV4P8EU65kSYsNOiZDVydR388/zMvLnPPhNeKVrkAf3qetMW21o1uC9U/kdOfJBXGWNvf42qzSCuBbJFzR+Xwpj6nxZ0ccvmh7dcetKju+gexzLMLmHe+tnU5CWwAkGMJ5EuTLkYS4MtCZjM1/4A=,iv:0VjQ2dh8nbgHWILlAdb+lvX9GvABIPhqHeivLPefXWU=,tag:5xaxCzWj+xl6F3sw867hMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
